== Conformance

TODO: WMO techregs for discovery, and how this document meets those techregs

Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document.

OGC API - Records provides a record metadata model in support of resource discovery.  This specification should be
regarded as an extension to OGC API - Records.  Conformance to this specification requires demonstrated conformance
to the applicable Conformance Classes of OGC API - Records.

Authors of discovery metadata records published within the WIS 2.0 catalogue are required to comply with the
WMO Core Metadata Profile.  WCMP discovery metadata shall be compliant with:

* OGC API - Records - Part 1: Core: Requirements Class: Record
* OGC API - Records - Part 1: Core: Requirements Class: Record Collection

Requirements in this specification shall take precedence over the specifications in  OGC API - Records.

The WMO Secretariat shall publish guidance material to assist authors of WCMP discovery metadata in maintaining
consistency betweeen metadata records, as well as quality assessment and reporting.

This specification identifies x (x) Conformance Classes.  Each Conformance Class has an associated Requirements Class.
The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.

The Requirements Classes for WCMP are

TODO: describe each Requirements Class
