== Data Distribution

Additionally, a record may contain both *links* and *properties.associations* properties.  The following provides an example of using associations for related resources of a record, as both traditional link relations as well as API resources via URI templates.

==== Example of the property associations title expressed in JSON

....
{
...
    "associations": [
        {
            "rel": "search",
            "type": "text/html",
            "title": "WOUDC - Data - Station List",
            "href": "https://woudc.org/data/stations"
        },
        {
            "rel": "item",
            "type": "image/png",
            "title": "World Ozone and Ultraviolet Radiation Data Centre (WOUDC) stations",
            "href": "https://geo.woudc.org/ows?service=WMS&version=1.3.0&request=GetMap&crs={crs}&bbox={bbox}&layers=stations&width={width}&height={height}&format=image/png",
            "templated": true,
            "variables": {
               "crs": {
                  "description": "...",
                  "type": "string",
                  "enum": [ "EPSG:4326", "EPSG:3857" ]
               },
               "bbox": {
                  "description": "...",
                  "type": "array",
                  "items": {
                     "type": "number",
                     "format": "double"
                  },
                  "minItems": 4,
                  "maxItems": 4
               },
               "width": {
                  "description": "...",
                  "type": "number",
                  "format": "integer",
                  "minimum": 600,
                  "maximum": 5000
               },
               "height": {
                  "description": "...",
                  "type": "number",
                  "format": "integer",
                  "minimum": 600,
                  "maximum": 5000
               }
            }
        }
    ]
    ...
 }
 ...
}
....
