=== Good quality description

==== WCMP properties

* `properties.description`

==== Rationale for measurement

The description facilitates ease of understanding and discovery and so is a key element of metadata information displayed as part of search results. Extensive and meaningful descriptive information allows for users to both understand and properly evaluate a metadata record and its respective resource in support of data access, visualization and exploitation.

In the context of WIS2 Global Discovery Catalogues, the product title and description are the two most relevant elements in the WCMP metadata record.

==== Measurement

The description shall not be too short or too long and not contain HTML markup. Spelling and grammar are correct. Bulletin templates should not be used to populate the description.

==== Guidance

The description should provide a clear and concise statement that enables the reader to understand the content of the dataset. For guidance when completing the description, consider the following:

===== Relevant recommendations

Aim to be understood by non-experts::
* Avoid adding a scientific description
Describe the contents of the resource and the key aspects or attributes that are represented::
* Limit information in the description to the specific resource that is being described, i.e. do not include general background information
* Explain briefly what is unique about this resource and, if appropriate, how it differs from similar resources
* State any other limiting information, such as time period of data validity or geographic coverage
Spell out uncommon acronyms only once::
* Avoid jargon and unexplained abbreviations
* Avoid spelling out commonly used acronyms which are already understood by the general public
Write using present or past tenses::
* Avoid using future verb tense when possible
Use simple paragraph(s) only::
* Avoid including HTML and CSV tables or extra spaces to control display of text
Add purpose of data resource where relevant (e.g. for survey data)::
* Avoid citing external sources to this resource
* Avoid copying text from a journal article verbatim because this can lead to copyright violation concerns. Additionally, abstracts for journal articles are not intended to describe the provided resource and do not meet the metadata requirements. Related papers can be referenced in the metadata record links.

===== Spell checking recommendations

* Dictionary by Merriam-Webster: America's most-trusted online dictionaryfootnote:[https://www.merriam-webster.com]
* Cambridge Dictionary | English Dictionary, Translations & Thesaurusfootnote:[https://dictionary.cambridge.org]

==== Examples

```json
"properties": {
    ...
    "description": "For WMO Information System 2.0 (WIS 2.0) DWD provides a Global Cache Service. It offers the possibility to download cached core data from a single source. An automatic download is made possible by messages that are distributed worldwide and contain the actual download link. Subscription to receive the messages is possible via Global Brokers. General notes: 1) Maximum message size is limited to 8192 bytes, 2) Connected Global Brokers are Global Broker MF and Global Broker CMA, 3) During the test phase the data is not yet cached for 24 hours",
    ...
}
```
==== Rules

.Good quality description implementation rules
|===
|Rule |Score

|The description has between 16 and 2048 characters
|1

|The description does not contain markup (HTML)
|1

|The description passes a basic spellcheck
|1

|The description _does not_ contain a bulletin template
|1
|===

*Total possible score: 4 (100%)*



