== Distribution providers

Metadata records should contain information regarding the distribution provider and how to contact them via email.

=== WCMP element(s)

* `$.properties.contacts[?(@.role=="distributor")]`
* `$.properties.contacts[?(@.role=="distributor")].emails`
* `$.properties.contacts[?(@.role=="distributor")].contactInstructions`

=== What is being measured

The presence of distribution provider information and supporting elements.

* distributor contact information (email, contact instructions)

=== Rationale for measurement

Information of the distributing provider allows the user to contact the distributor in case of anything related to accessing the data.

=== Rules for implementation

By detecting the presence of the distributor provider.  See WCMP2, clause 7.

.Distributor information implementation rules
[cols="1a,2"]
|===
|Rule |Score

|The distributor provider is included.
|1

|The distributor contact email is included.
|1

|The distributor contact instruction element is included.
|1

|===

*Total possible score: 3 (100%)*

=== Guidance to score well on this assessment

* Specify a distributor provider. Note that a distributor provider does not have to be the same as the main point of contact, principal investigator
* Specify an email for the distributor
* Specify contact instructions for the distributor

=== Examples

```json
"properties": {
  ...
  "contacts": [{
    ...
    {
        "organization": "WMO Lead Centre for Long-Range Forecast Multi-Model Ensemble",
        "phones": [
            {
			    "value": "+82-2-2181-0486",
                "role": "office"
			},
            {
			    "value": "+82-2-2181-0489",
                "role": "fax"
			}
        ],
        "emails": [
            {
                "value": "lc_lrfmme@korea.kr",
                "role": "work"
            }
        ],
        "addresses": [
            {
                "deliveryPoint": "61 16-GIL YEOUIDAEBANG-RO DONGJAK-GU SEOUL",
                "city": "SEOUL",
                "postalCode": "07062",
                "country": "Republic of Korea"
            }
        ],
        "contactInstructions": "email",
        "links": [
            {
                "href": "https://www.wmolc.org/"
            }
        ],
        "roles": [
            "distributor"
        ]
    }]
  ...
}
```
