== Distribution providers

Metadata records should contain information regarding the distribution provider and how to contact them.

=== WCMP element(s)

* `$.properties.providers[?(@.role=="distributor")]`
* `$.properties.providers[?(@.role=="distributor")].name`
* `$.properties.providers[?(@.role=="distributor")].contactInfo.email`

=== What is being measured

The presence of distribution provider information and supporting elements.

* distributor contact information (organization, email)

=== Rationale for measurement

Information of the distributing provider allows the user to contact the distributor in case of anything related to accessing the data.

=== Rules for implementation

By detecting the presence of the distributor provider.  See WCMP, clause 7.

.Distributor information implementation rules
[cols="1a,2"]
|===
|Rule |Score

|The distributor provider is included.
|1

|The distributor contact organization is included.
|1

|The distributor contact email is included.
|1

|===

*Total possible score: 3 (100%)*

=== Guidance to score well on this assessment

* Specify a distributor provider. Note that a distributor provider does not have to be the same as the main point of contact, principal investigator
* Specify an email for the distributor

=== Examples

```json
"properties": {
  ...
  "providers": [{
    ...
    {
        "name": "WMO Lead Centre for Long-Range Forecast Multi-Model Ensemble",
        "contactInfo": {
            "phone": {
			    "office": "+82-2-2181-0486",
				"fax": "+82-2-2181-0489"
			},
            "email": {
                "work": "lc_lrfmme@korea.kr"
            },
            "address": [
                {
                "deliveryPoint": "61 16-GIL YEOUIDAEBANG-RO DONGJAK-GU SEOUL",
                "city": "SEOUL",
                "postal-code": "07062",
                "country": "Republic of Korea"
                }
            ],
            "url": {
				"href": "https://www.wmolc.org/"
			}
        },
        "roles": [
            {
                "name": "distributor"
            }
        ]
    }]
  ...
}
```
