=== Graphic overview for metadata records

==== WCMP properties

* `$.links[?(@.rel=="preview")]`

==== Rationale for measurement

A graphic overview of the product provides the user with a high level preview which can assist with the initial assessment or evaluation as part of search results presentation.


==== Measurement

The presence of a `preview` link is checked that it contains a URL to a common web image file type.footnote:[https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#Common_image_file_types]

==== Guidance

In addition to the presence of the graphic overview image it would also be valuable to provide consistent image dimensions (e.g. 800x800 pixels) such that all images are normalized and scaling/alignment of overivew images can be applied consistently by web applications rendering search results.

Examples of catalogues displaying graphic overviews:

* https://gisc.dwd.de[GISC DWD]
* https://navigator.eumetsat.int/search?query=MSG%20RGB[EUMETSAT Product Navigator]

===== Examples

```json
{
  "rel": "preview",
  "type": "image/png",
  "title": "Browse graphic",
  "href": "https://example.org/path/to/browse.png"
}
```

==== Rules

.Graphic overview for metadata records implementation rules
|===
|Rule |Score

|A graphic overview element is present
|1

|A graphic overview URL resolves successfully
|1

|A graphic overview URL content is a common web image file type (check MIME type, content header/magic number)
|1

|===

*Total possible score: (present link + resolves + image file type) / (total graphic overviews * 3) (100%)

