== Graphic overview for non bulletins metadata records

=== WCMP element(s)

* `$.links[?(@.rel=="preview")]`

=== What is being measured

The presence of a `preview` link is checked that it contains a URL to a common web image file type.footnote:[https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#Common_image_file_types]

=== Rationale for measurement

Product graphic overviews provide the user with a high level preview of the product which can assist in a high level assessment and/or evaluation as part of search results presentation.

=== Rules for implementation

.Graphic overview for non bulletins metadata records implementation rules
|===
|Rule |Score

|A graphic overview element is present
|1

|A graphic overview URL resolves successfully
|1

|A graphic overview URL content is a common web image file type (check MIME type, content header/magic number)
|1

|===

*Total possible score: 3 (100%)*

=== Guidance to score well on this assessment

In addition to the presence of the graphic overview image it would also be valuable to provide consistent image dimensions (e.g. 800x800 pixels) such that all images are normalized and scaling/alignment of overivew images can be applied consistently by web applications rendering search results.

Examples of catalogues using such information are here:

* https://gisc.dwd.de[GISC DWD]
* https://navigator.eumetsat.int/search?query=MSG%20RGB[EUMETSAT Product Navigator]

=== Examples

```json
{
  "rel": "preview",
  "type": "image/png",
  "title": "Browse graphic",
  "href": "https://example.org/path/to/browse.png"
}
```
