== Links health

=== WCMP element(s)

Any property with linked information (URLs).

* `links[*].href`
* `properties[*].href`
* `properties[*].concepts.url`
* `properties[*].scheme`

=== What is being measured

The number of broken links in each individual metadata record.  Broken links include links which, when accessed, result in a 4xx or 5xx HTTP error.footnote:[https://httpstatuses.com]

Also being measured is the use of HTTPS (with a valid SSL certificate) as the link protocol throughout WIS Metadata.

=== Rationale for measurement

Broken links damage the user experience and gives the impression to users that a website is not maintained (88% of the online consumers are less likely to return to a site after a bad experiencefootnote:[https://review42.com/web-design-statistics]). In addition, having numerous broken links affects the reputation and rank of your website when indexed by mass market search engines.

HTTPS is increasingly becoming a requirement for numerous agencies as well as the suggested protocol vs. HTTP.  Having non-HTTPS links in a WCMP document often leads to mixed content errors in web applications deployed via HTTPS for example, and using AJAX/XHR design patterns. HTTPS supports secure, authoritative and trustworthy links as part of WIS Metadata.

=== Rules for implementation

.Links health implementation rules
|===
|Rule |Score

|Each valid link present
|1

|Each valid HTTPS link present
|1

|Each valid MQTTS link present
|1

|===

*Total possible score: (valid links + valid HTTPS links + valid MQTTS links) / (total links * 3) (100%)*

=== Guidance to score well on this assessment

Ensure that all links resolve and are accessible via HTTPS.

=== Examples

```json
"links": [
  ...
  {
    "rel": "search",
    "type": "text/html",
    "title": "WOUDC - Data - Station List",
    "href": "https://woudc.org/data/stations"
  },
  ...
]
```


```json
"links": [
  ...
  {
    "rel": "related",
    "type": "application/json",
    "title": "Global Broker (Toulouse)",
    "href": "mqtts://[yourAccount]:[yourPassword]@globalbroker.meteo.fr:8883/",
    "channel": "cache/a/wis2/#",
    "distribution": {
      "maxMSGsize": 4096,
      "unit": "bytes"
    }
  },
  ...
```

```json
"links": [
  ...
  {
    "rel": "subscribe",
    "type": "application/json",
    "title": "Global Broker (Toulouse)",
    "href": "mqtts://[yourAccount]:[yourPassword]@wis2.dwd.de:8883/",
    "channel": "cache/a/wis2/deu/dwd/data/core/weather/analysis-prediction/forecast/model/#"
  },
  ...
```
