=== Persistent identifiers

==== WCMP properties

* `properties.externalIds`

==== Rationale for measurement

Persistent identifiers allow data to be accessible and citable. They make research data easier to access, reuse and verify, thereby making it easier to build on previous work, conduct new research and avoid duplicating already existing work.

==== Measurement

Whether persistent identifier information is available, can be successfully identified, and provides citation instructions.

==== Guidance

* Provide a persistent identifier
* Provide a 'Cite as' template as a link object with `rel="cite-as"`

===== Examples 

```json
"properties": {
  ...
  "externalIds": [{
    "scheme": "doi",
    "value": "https://dx.doi.org/10.14287/10000001"
  }]
  ...
}
```

For a citation:

```json
"properties": {
    ...
    "links": [
    ...
    {
        "rel": "cite-as",
        "title": "Cite as: WMO/GAW Ozone Monitoring Community, World Meteorological Organization-Global Atmosphere Watch Program (WMO-GAW)/World Ozone and Ultraviolet Radiation Data Centre (WOUDC) [Data]. Retrieved [YYYY-MM-DD], from https://woudc.org. A list of all contributors is available on the website. doi:10.14287/10000004",
        "type": "text/html",
        "href": "https://dx.doi.org/10.14287/10000004"
    }]
  ...
}
```
=== Rules

.Persistent identifiers implementation rules
|===
|Rule |Score

|The external identifiers object is present
|1

|At least one scheme is equal to `doi`, `ark`, or `hdl`
|1

|At least one citation exists as a link object with `rel="cite-as"`
|1
|===

*Total possible score: 3 (100%)*

