== Distribution providers

Metadata records should contain information regarding how to access the data
which it is describing.

=== WCMP element(s)

* `$.properties.providers[?(@.role=="distributor")]`
* `$.properties.providers[?(@.role=="distributor")].name
* `$.properties.providers[?(@.role=="distributor")].contactInfo.email


```json
{
  "name": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
  "individual": "National Inquiry Response Team / \u00c9quipe nationale de r\u00e9ponse des demandes du public",
  "positionName": "National Inquiry Response Team",
  "contactInfo": {
    "phone": {
      "office": "+01-819-997-2800"
    },
    "email": {
      "office": "+01-506-451-6010"
    },
    "address": {
      "office": {
        "deliveryPoint": "77 Westmorland Street, suite 260",
        "city": "Fredericton",
        "administrativeArea": "NB",
        "postalCode": "E3B 6Z4",
        "country": "Canada"
      },
      "onlineResource": {
        "href": "https://www.canada.ca/en/environment-climate-change.html"
      }
    },
    "hoursOfService": "0700h - 1500h EST",
    "contactInstructions": "email",
    "url": {
      "rel": "canonical",
      "type": "text/html",
      "href": "https://www.canada.ca/en/environment-climate-change.html"
    }
  },
  "roles": [{
    "name": "pointOfContact"
  }]
}
```

=== What is being measured

The presence of distribution information and supporting elements.

* distributor contact information (organization, email)

=== Rationale for measurement

Distribution information provides the necessary information for accessing the
data and contact information for the data distributor.

=== Rules for implementation

By detecting the presence of the distributor provider.  See WCMP2, clause 7.

.Distribution information implementation rules
[cols="1a,2"]
|===
|Rule |Score

|distributor provider is included
|1

|distributor contact organization is included
|1

|distributor contact email is included
|1

|===

*Total possible score: 3 (100%)*

=== Guidance to score well on this assessment

* Specify a distributor provider. Note that a distributor provider does not
  have to be the same as the main point of contact, principal investigator
* Specify an email for the distributor

