== Temporal information

=== WCMP Element(s)

* `time`

=== What is being measured

* temporal extent: This element describes the period of time that the available product covers
* temporal resolution: The temporal frequency at which the data is updated (i.e. every x hours, days, etc.)

=== Rationale for measurement

Temporal information is a significant characteristic of weather/climate/water
data and as such is critical for users to know which period(s) of time is/are
covered by products and how often new products are received.

=== Rules for implementation

The temporal extent is present in `time`:

```json
"time": {
  "interval" : ["2020-10-30", "2021-10-30"]
}
```

In the case of an ongoing dataset with a known start date and unknown end
date, the end date must be indicated with `..`.  For instance,
where a dataset is from 2020-10-30 onwards:

```json
"time": {
  "interval" : ["2020-10-30", ".."]
}
```

It is also recommended to provide a temporal resolution to convey the temroal granularity of the dataset.
The following example provides an example for daily data.

```json
"time": {
  "interval" : ["2020-10-30", ".."],
  "resolution": "P1D"
}
```

.Temporal information implementation rules

|===
|Rule |Score

|The temporal extent is present
|1

|The begin and end components are present in the temporal extent
|1

|The begin date time is less than or equal to the end date time
|1

|The temporal resolution is present
|1

|===

*Total possible score: 4 (100%)*

=== Guidance to score well on this assessment

Ensure that the temporal extent resolution is present in the metadata record.

