== Time Intervals

=== WCMP Element(s)

* `time.interval`
* (`additionalElements.temporal.interval`)

=== What is being measured

Whether a time interval is present and contains an interval with a corresponding resolution. 

=== Rationale for measurement

Temporal information is a significant characteristic of weather/climate/water data and as such is critical for users to know which period(s) of time is/are covered by products and how often new products are received.

=== Rules for implementation

.Temporal information implementation rules
|===
|Rule |Score

|The begin is less than or equal to the end or open.
|1

|Only one of the interval extents may be open (begin or end but not both).
|1

|For every interval there is a corresponding resolution present.
|1

|===

*Total possible score: 3 (100%)*

=== Guidance to score well on this assessment

Ensure that the temporal extent resolution is present in the metadata record.

=== Examples

```json
"time": {
  "interval" : ["2020-10-30", ".."],
  "resolution": "P1D"
}
```
