=== Time intervals

==== WCMP properties

* `time.interval`
* `additionalElements.temporal.interval`

==== Rationale for measurement

Temporal information is a significant characteristic of weather, climate, and water data and is critical for users to know which time periods are covered by products and how often new products are received.

==== Measurement

The time interval is present and contains and has a corresponding resolution. 

==== Guidance

A temporal interval and its associated resolution should be expressed for data that is generated with a given frequency or cadence.  For example, for ongoing hourly weather observations, express a temporal interval with an "open ended" end time (e.g. `..`) and the `resolution` as an ISO 8601 Duration.

===== Examples

```json
"time": {
  "interval" : ["2020-10-30", ".."],
  "resolution": "P1D"
}
```

==== Rules

.Temporal information implementation rules
|===
|Rule |Score

|The begin is less than the end or open.
|1

|Only one of the interval extents may be open (begin or end but not both).
|1

|For every interval there is a corresponding resolution present.
|1

|===

*Total possible score: (begin less than end + only one interval open + resolution) / (total intervals * 3) (100%)

