=== Time intervals

==== WCMP properties

* `time.interval`
* `additionalElements.temporal.interval`

==== Rationale for measurement

Temporal information is a significant characteristic of weather/climate/water data and as such is critical for users to know which period(s) of time is/are covered by products and how often new products are received.

==== Measurement

Whether a time interval is present and contains an interval with a corresponding resolution. 

==== Guidance

Ensure that the temporal extent resolution is present in the metadata record.

===== Examples

```json
"time": {
  "interval" : ["2020-10-30", ".."],
  "resolution": "P1D"
}
```

==== Rules

.Temporal information implementation rules
|===
|Rule |Score

|The begin is less than the end or open.
|1

|Only one of the interval extents may be open (begin or end but not both).
|1

|For every interval there is a corresponding resolution present.
|1

|===

*Total possible score: (begin less than end + only one interval open + resolution) / (total intervals * 3) (100%)

