== Good quality title

=== WCMP element(s)

* `properties.title`

=== What is being measured

The title shall always be populated and follow the principles of WCMP guidance. The length shall not be too short or too long, contain less than 3 acronyms and represented in title case. Spelling and grammar are correct.

=== Rationale for measurement

The title is the first element of metadata information displayed and helps with initial identification. Meaningful and relevant information makes it easier for users to understand the resource.

In the context of WIS2 Global Discovery Catalogues, the product title and description are the two most relevant elements in the WCMP metadata record. These two elements are presented to the users in search results as well as the product description page, and need to focus on highlighting the product’s key characteristics to assist users with relevant product search results.

=== Rules for implementation

.Good quality title implementation rules
|===
|Rule |Score

|The title is present
|1

|The title has 3 words or more
|1

|The title has 150 characters or less
|1

|The title has only printable characters (numbers and letters)
|1

|The words in title are represented in "Title Case"
|1

|The title contains less than 3 acronyms (words with all upper case)
|1

a|The title _does not_ contain bulletin header (regular expression: `[A-Z]{4}\d{2}[\s_]*[A-Z]{4}`)
|1

|The title passes a basic spellcheck
|1
|===

*Total possible score: 8 (100%)*

=== Guidance to score well on this assessment

The title should be as specific as possible. For example, if the product only contains one parameter, this can be stated in the title; however, if the product contains numerous parameters, then a more general term should be used in the title, and the parameters stated elsewhere in the metadata record (description, themes, keywords, etc.).

