== The WMO Core Metadata Profile Record

A WCMP record provides descriptive information about a dataset made available
through WIS 2.0.

=== Conformance Class Core

The WCMP Core Conformance Class provides requirements to articulate the required elements
of a WCMP discovery metadata record.

include::../requirements/requirements_class_core.adoc[]

==== Validation

The WCMP record schema is based on the schema defined as part of OGC API - Records - Part 1:
Core: Requirements Class: Record Core and the associated information model.  WCMP records which
are valid to WCMP are therefore valid to the OGC API - Records record schema.

include::../requirements/core/REQ_validation.adoc[]

==== Identifier

A WCMP record utilizes the OARec `+id+` property to provide a unique identifier
to a dataset.  A record identifier is essential for querying and identifying
records within the GDC.

[source,json]
----
"id": "urn:x-wmo:md:ca.gc.ec.msc:observations.swob"
----

include::../requirements/core/REQ_identifier.adoc[]

==== Conformance

A WCMP record leverages the OGC API `+conformsTo+` property to identify the conformance classes
that apply to the record.  WCMP conformance identification is valuable for content/version
detection and handling.

[source,json]
----
"conformsTo": [
  "http://wis.wmo.int/spec/wcmp/2.0"
]
----

include::../requirements/core/REQ_conformance.adoc[]

==== Properties Type

WCMP records provide descriptive information about a number of different resource types, such as
dataset or services.

[source,json]
----
"type": "dataset"
----

include::../requirements/core/REQ_type.adoc[]

==== Geometry

WCMP records provide descriptive information regarding the spatial properties of a dataset. Spatial
information provides a useful indicator of the location of the dataset and facilitates searching the
Global Discovery Catalogue with spatial predicates.

[source,json]
----
"geometry": {
    "type": "Polygon",
    "coordinates": [
        [
            [
                -142.23,
                28.0123
            ],
            [
                -142.23,
                82.456
            ],
            [
                -52.16,
                82.456
            ],
            [
                -52.16,
                28.0123
            ],
            [
                -142.23,
                28.0123
            ]
        ]
    ]
}
----

include::../requirements/core/REQ_geometry.adoc[]

==== Title

A WCMP record's `+properties.title+` property is a human-readable name for a given dataset.

[source,json]
----
"title": "Surface weather observations"
----

include::../requirements/core/REQ_title.adoc[]

==== Description

A WCMP record have a `+properties.description+` property, which is a free-text summary description of the
resource the provider wishes to make discoverable.

[source,json]
----
"description": "Surface observations measured at the automatic and manual stations of the Environment and Climate Change Canada and partners networks, either for a single station, or for the stations of specific provinces and territories (last 30 days)"
----

include::../requirements/core/REQ_description.adoc[]

==== Keywords

A WCMP record should have a `+properties.keywords+` property, typically represented using keywords, tags, key
phrases, or classification codes.

[source,json]
----
"keywords": [
  "surface",
  "observations",
  "weather",
  "real-time"
]
----

include::../recommendations/core/REC_keywords.adoc[]

==== Themes and Topic Hierarchy

A WCMP record has a `+properties.themes+` property, which is a knowledge organization system used to classify
the data that the record is describing.  A WCMP can have one or more themes.  The WIS Topic Hierarchy is put
forth as a specific theme/concept.

[source,json]
----
"themes": [
  {
    "concepts": [
      "weather"
    ],
    "scheme": "https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/earth-system-domain.csv"
----

include::../requirements/core/REQ_themes_topic_hierarchy.adoc[]

==== Geospatial Extent

A WCMP record has a `+properties.extent.spatial.bbox+` item property, which provides the ability to list 1..n 
minimum bounding geometries for a given dataset, where:

* minx: westernmost coordinate of the limit of the dataset extent, expressed in longitude decimal degrees as a
signed number between -180 and 180, less than or equal to maxx
* miny: southernmost coordinate of the limit of the dataset extent, expressed in latitude decimal degrees as a
signed number between -90 and 90, less than or equal to maxy
* maxx: easternmost coordinate of the limit of the dataset extent, expressed in longitude decimal degrees as a
signed number between -180 and 180, greater than or equal to minx
* maxy: northernmost coordinate of the limit of the dataset extent, expressed in latitude decimal degrees as a
signed number between -90 and 90, greater than or equal to miny

This property also facilitates catalogue searches with spatial predicate (within extent, etc.).

TODO: resolve https://github.com/opengeospatial/ogcapi-records/issues/168

[source,json]
----
"extent": {
  "spatial": {
    "bbox": [
      [
        -142,
        42,
        -52,
        84
      ]
    ],
    "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
  }
}
----

include::../requirements/core/REQ_geospatial_extent.adoc[]
include::../recommendations/core/REC_geospatial_extent-brevity.adoc[]
include::../recommendations/core/REC_geospatial_extent-point.adoc[]
include::../recommendations/core/PER_geospatial_extent.adoc[]

==== Temporal Extent

A WCMP record has a `+properties.extent.temporal+` item property, which provides the ability to list 1..n
temporal extents as time instants or time periods.  Temporal extents can be fully bound or open in either direction
(e.g. until or before.  A `+properties.extent.temporal.resolution+` property is able express the temporal granularity
at which a given dataset's data is measured/generated/reported.

[source,json]
----
"extent": {
  "temporal": {
    "interval": [
      [
        "1924-08-18",
        null
      ]
    ],
    "resolution": "P1H",
    "trs": "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"
  }
}
----

include::../requirements/core/REQ_temporal_extent.adoc[]
include::../recommendations/core/REC_temporal_extent.adoc[]

==== Providers

A WCMP record has providers defined as part of the `+properties.providers+` property. These elements
provide contact information based on the role of the provider.

[source,json]
----
"providers": [
  {
    "name": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
    "individual": "National Inquiry Response Team / \u00c9quipe nationale de r\u00e9ponse des demandes du public",
    "positionName": "National Inquiry Response Team",
    "contactInfo": {
      "phone": {
        "office": "+01-819-997-2800"
      },
      "email": {
        "office": "+01-506-451-6010"
      },
      "address": {
        "office": {
          "deliveryPoint": "77 Westmorland Street, suite 260",
          "city": "Fredericton",
          "administrativeArea": "NB",
          "postalCode": "E3B 6Z4",
          "country": "Canada"
        },
        "onlineResource": {
          "href": "https://www.canada.ca/en/environment-climate-change.html"
        }
      },
      "hoursOfService": "0700h - 1500h EST",
      "contactInstructions": "email",
      "url": {
        "rel": "canonical",
        "type": "text/html",
        "href": "https://www.canada.ca/en/environment-climate-change.html"
      }
    },
    "roles": [
      {
        "name": "pointOfContact"
      },
      {
        "name": "originator"
      }
    ]
  }
]
----

include::../requirements/core/REQ_providers.adoc[]

==== Version

Datasets can typically be versioned by an organization (version of an NWP model, processing chain/workflow, etc.).  Data
providers may choose to make this information available to the user when providing multiple versions of a dataset
over time.

[source,json]
----
"version": "0.1.0"
----

include::../recommendations/core/PER_version.adoc[]

==== Digital Object Identifier

A digital object identifier (DOI) is a persistent identifier or handle used to identify various objects uniquely,
and is widely in scientific publications.

[source,json]
----
"externalIds": [
  {
    "scheme": "doi",
    "value": "fake-doi-prefix/fake-doi-suffix"
  }
]
----

include::../recommendations/core/PER_doi.adoc[]
include::../recommendations/core/REC_doi.adoc[]

==== Record Creation Date

A WCMP record has a `+properties.recordCreated+` property, which describes the date that the record was created.

[source,json]
----
"recordCreated": "2021-06-12T23:45:24Z"
----

include::../requirements/core/REQ_record_creation_date.adoc[]

==== Record Update Date

A WCMP record has a `+properties.recordUpdated+` property, which describes the date that the record was changed.

[source,json]
----
"recordUpdated": "2022-06-12T18:52:39Z"
----

include::../requirements/core/REQ_record_update_date.adoc[]

==== WMO Data Policy

Based on the WMO Unified Data Policy Resolution (Res.1) footnote:[https://library.wmo.int/doc_num.php?explnum_id=11113#page=9], exchanged data
are classified as `+core+` or `+recommended+`.

include::../requirements/core/REQ_data_policy.adoc[]

If the resource is classified as `+recommended+`, it needs to be indicated if any additional conditions apply.  Conditions on use are essential for the WMO Unified Data Policy, but for transparency and clarification any other conditions should also be indicated.

include::../requirements/core/REQ_data_policy_conditions.adoc[]

.Example: Core Data
[source,json]
----
"wmo:dataPolicy": {
    "name": "core"
}
----

.Example: Recommended Data with no additional conditions
[source,json]
----
"wmo:dataPolicy": {
    "name": "recommended",
    "additionalConditions": [
        {
            "name": "none"
        }
    ]
}
----

.Example: Recommended Data with additional conditions
[source,json]
----
"wmo:dataPolicy": {
    "name": "recommended",
    "additionalConditions": [
        {
            "name": "copyright",
            "scheme": "https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode"
        }
    ]
}
----

For having the most detailed information about data policy and additional conditions it is useful to add provider-specific context.
include::../recommendations/core/REC_data_policy_conditions.adoc[]

.Example: Recommended Data with additional conditions and provider-specific context
[source,json]
----
"wmo:dataPolicy": {
    "name": "recommended",
    "additionalConditions": [
        {
            "name": "license",
            "scheme": "https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode",
            "link": {
                "href": "https://www.eumetsat.int/eumetsat-data-licensing",
                "title": "EUMETSAT DATA LICENSING"
            }
        }
    ]
}
----


==== Distribution Information

===== Overview

A WCMP record provides information regarding how to access and retrieve data. This information is specified by defining a `+links+` array property, with one or more objects to corresponding data access services.

===== Examples

- *_Adding the MQTT information_*

Below is an example of two link objects, providing both search and MQTT subscription information:

[source,json]
----
"links": [
  {
    "rel": "search",
    "type": "text/html",
    "title": "WOUDC - Data - Station List",
    "href": "https://woudc.org/data/stations"
  },
  {
    "rel"  : "data",
    "type" : "application/json",
    "title": "WIS2 notification service",
    "href" : "mqtt://example.org",
    "wmo:topic": "wis2/mytopic"
  }
]
----

- *_Example with the mandatory distribution information_*

Below is provided an example link object of a WMS service providing API access to images:

[source,json]
----
{
  "rel": "item",
  "type": "image/png",
  "title": "Eumetview",
  "href": "https://view.eumetsat.int/geoserver/ows?service=WMS&request=GetMap&version=1.3.0&layers=msg_fes:ir108&styles=&format={format}&crs={crs}&bbox={bbox}&width={width}&height={height}",
  "templated": true,
  "variables": {
    "crs": {
      "description": "...",
      "type": "string",
      "enum": [
        "EPSG:4326",
        "EPSG:3857"
      ]
    },
    "bbox": {
      "description": "...",
      "type": "array",
      "items": {
        "type": "number",
        "format": "double"
      },
      "minItems": 4,
      "maxItems": 4
    },
    "width": {
      "description": "...",
      "type": "number",
      "format": "integer",
      "minimum": 600,
      "maximum": 5000
    },
    "height": {
      "description": "...",
      "type": "number",
      "format": "integer",
      "minimum": 600,
      "maximum": 5000
    },
    "format": {
      "description": "...",
      "type": "string",
      "enum": [
        "image/geotiff",
        "image/geotiff8",
        "image/gif",
        "image/jpeg",
        "image/png; mode=8bit"
      ]
    },
    "sampleRequest": "https://view.eumetsat.int/geoserver/ows?service=WMS&request=GetMap&version=1.3.0&layers=msg_fes:ir108&styles=&format=image/jpeg&crs=EPSG:4326&bbox=-77,-77,77,77&width=800&height=800"
  }
}
----

- *_Example with the complete distribution information_*

Additional distribution information is added to allow creating more comprehensive discovery services. Below is an example of such distribution information.

[source,json]
----
{
  "rel": "service",
  "type": "text/html",
  "title": "EUMETSAT Datastore",
  "href": "https://data.eumetsat.int/data/map/EO:EUM:DAT:MSG:MSG15-RSS",
  "distribution": {
    "availableFormats": [
      {
        "name": "native",
        "description": "This is sent in a compressed Submission Information Package (SIP) by default.",
        "numberOfFiles": "288 per day",
        "typicalFilesize": "60 MB",
        "typicalFilename": "MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip",
        "samples": "https://data.eumetsat.int/data/access/MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip",
        "documentation": {
          "rel": "alternate",
          "type": "text/html",
          "title": "SIP documentation and tools",
          "href": "https://www.eumetsat.int/formats#SIP"
        }
      }
    ]
  }
}
----

include::../requirements/core/REQ_links.adoc[]
include::../recommendations/core/REC_distribution.adoc[]
include::../recommendations/core/REC_links.adoc[]
