== The WMO Core Metadata Profile Record

A WCMP record provides descriptive information about a dataset made available
through WIS2.

=== Conformance Class Core

==== Overview

The WCMP Core Conformance Class provides requirements to articulate the required elements
of a WCMP discovery metadata record.

include::../requirements/requirements_class_core.adoc[]


The table below provides an overview of the set of properties that may be included in a WCMP record.


.WCMP record core properties
|===
|Property|Requirement|Description

|``id``
|**required**
|A unique identifier to the dataset (see <<_identifier>>)

|``type``
|**required**
|A fixed value denoting the record as a GeoJSON ``Feature`` (see <<_validation>>)

|``conformsTo``
|**required**
|The version of WCMP associated that the record conforms to (see <<_conformance_2>>)

|``properties.type``
|**required**
|The resource type described by the record (see <<_properties_type>>)

|``properties.title``
|**required**
|A human-readable name for a given dataset (see <<_properties_title>>)

|``properties.description``
|**required**
|A free-text summary description of the dataset (see <<_properties_description>>)

|``properties.keywords``
|optional
|Keywords, tags, key phrases, or classification codes (see <<_properties_keywords>>)

|``properties.themes``
|**required**
|Classifiers, categories and controlled vocabularies (see <<_properties_themes>>)

|``geometry``
|**required**
|Geospatial location associated with the dataset, in a geographic coordinate reference system (see <<_geospatial_extent>>)

|``time``
|**required**
|Temporal extent associated with a dataset (see <<_temporal_extent>>)

|``additionalExtents.spatial``
|optional
|Additional geospatial extents in other coordinate reference systems (see <<_additional_geospatial_extents>>)

|``additionalExtents.temporal``
|optional
|Additional time instants or periods (see <<_additional_temporal_extents>>)

|``properties.contacts``
|**required**
|Contact information for the dataset (see <<_properties_contacts>>)

|``properties.version``
|optional
|Version or edition of the dataset (see <<_properties_version>>)

|``properties.externalIds``
|optional
|Persistent identifiers or handles for the dataset (see <<_properties_persistent_identifiers>>)

|``properties.created``
|**required**
|The date that the record was created (see <<_properties_record_creation_date>>)

|``properties.updated``
|optional
|The date that the record was updated (see <<_properties_record_update_date>>)

|``properties.wmo:dataPolicy``
|**conditional**
|WMO data policy as per Resolution 1 (Cg-Ext(2021) footnote:[https://library.wmo.int/doc_num.php?explnum_id=11113#page=9].  **Required** for datasets (see <<_properties_wmo_data_policy>>)

|``links``
|**required**
|Online linkages to data retrieval or additional resources associated with the dataset (see <<links-distribution>>)

|``properties.*``
|optional
|Additional properties as required (see <<_additional_properties>>)

|===

==== Validation

The WCMP record schema is based on  _OGC API - Records - Part 1: Core: Requirements Class: Record Core_ schema and the associated information model.  WCMP records compliant with WCMP schema are therefore compliant with the _OGC API - Records_ record schema.

include::../requirements/core/REQ_validation.adoc[]

==== Identifier

The `+id+` property is a unique identifier
of the dataset.  A record identifier is essential for querying and identifying
records within the GDC.

include::../requirements/core/REQ_identifier.adoc[]

.Example

[source,json]
----
"id": "urn:x-wmo:md:can:eccc-msc:observations.swob"
----

==== Conformance

The `+conformsTo+` property to identifies the version ofthe WCMP standard that the metadata record conforms to. Conformance identification is valuable for version
detection and handling of content.

include::../requirements/core/REQ_conformance.adoc[]

.Example

[source,json]
----
"conformsTo": [
  "http://wis.wmo.int/spec/wcmp/2/conf/core"
]
----

==== Properties / Type

The `+type+` property identifies the type of resource that the metadata record describes using values from the resource type codelist. While most metadata records will be set to `dataset`,
WCMP can also describe services and processes. See the resource type codelist footnote:[https://github.com/wmo-im/wcmp2-codelists/blob/main/codelists/resource-type.csv] for
allowed values.

include::../requirements/core/REQ_type.adoc[]
include::../requirements/core/REQ_type_service.adoc[]

.Example

[source,json]
----
"properties": {
  ...
  "type": "dataset"
  ...
}
----

==== Properties / Title

The `+title+` property is a human-readable name of the dataset.

include::../requirements/core/REQ_title.adoc[]

.Example

[source,json]
----
"properties": {
  ...
  "title": "Surface weather observations"
  ...
}
----

==== Properties / Description

The `+description+` property is a free-text summary of the dataset.

.Example

include::../requirements/core/REQ_description.adoc[]

[source,json]
----
"properties": {
  ...
  "description": "Surface observations measured at the automatic and manual stations of the Environment and Climate Change Canada and partners networks, either for a single station or for the stations of specific provinces and territories (last 30 days)."
  ...
}
----

==== Properties / Keywords

The `+keywords+` property is a list keywords, tags, specific phrases, or classification codes associated with the resource, but are not referenced to a particular vocabulary or knowledge organization system.

include::../recommendations/core/REC_keywords.adoc[]

.Example

[source,json]
----
"properties": {
  ...
  "keywords": [
    "surface",
    "observations",
    "weather",
    "real-time"
  ]
  ...
}
----

==== Properties / Themes

The `+themes+` property is a list of concepts that are referenced to a vocabulary or knowledge organization system used to classify the resource.  A concept's `+id+`
provides an identifier for the given concept, as well as optional `+title+`, `+description+` and `+url+` properties to further describe the concept as desired.

A theme's `+scheme+` property provides a remote reference to a controlled vocabulary, codelist or knowledge organization system.

A concept's optional `+url+` property can provide a remote reference to a given concept (for example, to an online ontology or code registry).

A WCMP metadata record can have one or more themes.

include::../requirements/core/REQ_themes.adoc[]
include::../requirements/core/REQ_themes_wis2_global_service.adoc[]
include::../recommendations/core/REC_granularity.adoc[]

.Examples
[source,json]
----
"properties": {
  ...
  "themes": [
    {
      "concepts": [
        {
          "id": "Temperature",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/_0-0-0"
        },
        {
          "id": "Relative humidity",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/_0-1-1"
        },
        {
          "id": "u-component of Wind",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/_0-2-2"
        },
        {
          "id": "v-component of Wind",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/_0-2-3"
        }
      ],
      "scheme": "http://codes.wmo.int/grib2/codeflag/4.2"
    }
  ]
  ...
}
----

[source,json]
----
"themes": [
  {
    "concepts": [
      {
        "id": "Temperature/air temperature",
        "url": "http://codes.wmo.int/bufr4/b/12/_001"
      },
      {
        "id": "Dewpoint temperature",
        "url": "http://codes.wmo.int/bufr4/b/12/_003"
      }
    ],
    "scheme": "http://codes.wmo.int/bufr4/b"
  }
]
----

[source,json]
----
"properties": {
  ...
  "themes": [
    {
      "concepts": [{
        "id": "weather",
        "url": "https://github.com/wmo-im/wis2-topic-hierarchy/blob/main/topic-hierarchy/earth-system-discipline.csv#L2"
      }],
      "scheme": "https://github.com/wmo-im/wis2-topic-hierarchy/blob/main/topic-hierarchy/earth-system-discipline.csv"
    }
  ]
  ...
}
----


==== Geospatial and Temporal Extents

===== Geospatial Extent
The `+geometry+` property is the general bounding spatial extent of the dataset in the geographic coordinate system.  
Geospatial bounding
extents provide a useful indicator of the location of the dataset to facilitate search and map displays in the GDC.

include::../requirements/core/REQ_extent_geospatial.adoc[]
include::../recommendations/core/REC_extent_geospatial_point.adoc[]
include::../recommendations/core/REC_extent_geospatial_precision.adoc[]
include::../recommendations/core/REC_extent_geospatial_wis2_global_service.adoc[]

.Examples

[source,json]
----
"geometry": {
    "type": "Polygon",
    "coordinates": [[
            [-142.23, 28.03],
            [-142.23, 82.56],
            [-52.16, 82.56],
            [-52.16, 28.03],
            [-142.23, 28.03]
    ]]
}
----

[source,json]
----
"geometry": {
    "type": "Point",
    "coordinates": [-79.38, 43.65]
}
----

[source,json]
----
"geometry": null
----

===== Additional Geospatial Extents
The `+additionalExtents.spatial+` property is for other geospatial extents associated with the dataset, for example, non-geographic data or for describing multiple sub-areas of a dataset.
The `+additionalExtents.spatial.bbox+` property
provides the ability to list one to many minimum bounding geometries for a given dataset, where:

* minx is the westernmost coordinate of the limit of the dataset extent, expressed in longitude decimal degrees as a
signed number between -180 and 180, less than or equal to maxx.
* miny is the southernmost coordinate of the limit of the dataset extent, expressed in latitude decimal degrees as a
signed number between -90 and 90, less than or equal to maxy.
* maxx is the easternmost coordinate of the limit of the dataset extent, expressed in longitude decimal degrees as a
signed number between -180 and 180, greater than or equal to minx.
* maxy is the northernmost coordinate of the limit of the dataset extent, expressed in latitude decimal degrees as a
signed number between -90 and 90, greater than or equal to miny.

This property also facilitates catalogue searches with geospatial predicate (within extent, etc.).

include::../recommendations/core/PER_extent_geospatial.adoc[]

.Example

[source,json]
----
"additionalExtents": {
  "spatial": {
    "bbox": [
      [-142, 42, -52, 84]
    ],
    "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
  }
}
----

===== Temporal Extent
The `+time+` property describes the general bounding extent of the dataset and the temporal resolution. 

Temporal extents provide a useful indicator of the date and time period of the dataset and facilitates temporal searching in the GDC. 

Temporal resolution provides a useful indicator of the data update frequency (for example, for real-time datasets).

include::../requirements/core/REQ_extent_temporal.adoc[]
include::../recommendations/core/REC_extent_temporal.adoc[]
include::../recommendations/core/PER_extent_temporal_service.adoc[]

.Examples

[source,json]
----
"time": {
  "date": "2021-10-30"
}
----

[source,json]
----
"time": {
  "timestamp": "2021-10-30T11:11:11Z"
}
----

[source,json]
----
"time": {
  "interval" : ["2020-10-30", "2021-10-30"],
  "resolution": "P1D"
}
----

[source,json]
----
"time": {
  "interval": [
    ["R/T00Z", "PT180H"],
    ["R/T12Z", "PT180H"]
  ],
  "resolution": "PT6H"
}
----

[source,json]
----
"time": null
----

If only times are given for the interval, it is implicitly assumed that those are recurring every day.

[source,json]
----
"time": {
  "interval" : ["T00Z", "T23Z"],
  "resolution": "PT1H"
}
----

Some cases might be more complex due to the product's characteristics.

The example below describes two intervals with the model run time (start) up to the range covered by the model run (end). Here, the end of the interval is characterised by a time period. Additionally, the time steps within the model range are relevant information (resolution).

To ensure clarity, an additional human-readable explanation is given in the `+properties.description+`.
Further time-related characteristics (e.g. frequency of modifications, available data, etc.) should be added in `+properties.themes+`.

.Example: complex time information with additional explanation and characteristics

[source,json]
----
"time": {
    "interval": [
        ["T00Z", "PT180H"],
        ["T12Z", "PT180H"]
    ],
    "resolution": "PT6H"
},
"properties": {
    ...
    "description": "[...] up to +180h every 6h, runs 00/12 UTC [...]."
    ...
    "themes": [
        {
        "concepts": [
            {"id": "continual"}
        ],
        "scheme": "https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_FrequencyCode"
        }
        ...
    ]
    ...
}
----

If necessary, further granularity can be indicated by the `+additionalExtents.temporal+` property.

===== Additional Temporal Extents

The `+additionalExtents.temporal+` property is for describing other temporal extents associated with the dataset, for example, multiple time instances or to identify other temporal reference systems. 

Temporal extents can be fully bound or open in either direction (e.g., until or before).  An `+additionalExtents.temporal.resolution+`
property is able express the temporal granularity at which a given dataset's data is measured, generated, or reported.

include::../recommendations/core/PER_extent_temporal.adoc[]

.Example

[source,json]
----
"additionalExtents": {
  "temporal": {
    "interval": [
      [
        "1924-08-18",
        null
      ]
    ],
    "resolution": "P1H",
    "trs": "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"
  }
}
----

==== Properties / Contacts

The `+contacts+` property is the information associated with one or more responsible parties of the resource.

include::../requirements/core/REQ_contacts.adoc[]
include::../recommendations/core/PER_contacts.adoc[]

.Examples

[source,json]
----
"properties": {
  ...
  "contacts": [{
      "identifier": "ECCC",
      "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
      "positionName": "National Inquiry Response Team",
      "phones": [{
        "value": "+18199972800"
      }],
      "emails": [{
        "value":"enviroinfo@ec.gc.ca"
      }],
      "addresses": [{
        "deliveryPoint": "77 Westmorland Street, suite 260",
        "city": "Fredericton",
        "administrativeArea": "NB",
        "postalCode": "E3B 6Z4",
        "country": "Canada"
      }],
      "links": [{
        "href": "https://www.canada.ca/en/environment-climate-change.html"
      }],
      "contactInstructions": "email",
      "roles": ["producer", "host"]
  }]
  ...
}
----

Note that a contact can also be specified by using a URL:

[source,json]
----
"properties": {
  ...
  "contacts": [{
      "name": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
      "links": [{
          "href": "https://www.canada.ca/en/environment-climate-change/corporate/contact.html"
      }]
  ]
  ...
}
----

==== Properties / Version

The `+version+` property is the version of the dataset. Datasets may be versioned by an organization, for example, the version of an NWP model or a processing chain/workflow, and data providers can make this information available when there are multiple versions of a dataset over time.

include::../recommendations/core/PER_version.adoc[]

.Example

[source,json]
----
"properties": {
  ...
  "version": "0.1.0"
  ...
}
----

==== Properties / Persistent Identifiers

The `+externalIds+` property is a persistent (or handle) identifier used to provide a long lasting reference to a digital resource.  Persistent identifiers
are commonly used for scientific publications and datasets.

Examples of persistent identifiers include, but are not limited to:

* Digital Object Identifiers (DOI) footnote:[https://doi.org]
* Archival Resource Key (ARK) footnote:[https://arks.org]
* Handle footnote:[https://handle.net]

include::../recommendations/core/REC_pids.adoc[]
include::../recommendations/core/PER_pids.adoc[]

.Example

[source,json]
----
"properties": {
  ...
  "externalIds": [{
    "scheme": "doi",
    "value": "10.14287/10000001"
  }, {
    "scheme": "hdl",
    "value": "2381/12775"
  }, {
    "scheme": "ark",
    "value": "ark:/13030/tf5p30086k"
  } ]
  ...
}
----

.Example: Online citation

[source,json]
----
"links": [
  {
    "rel": "cite-as",
    "title": "Cite as: WMO/GAW Ozone Monitoring Community, World Meteorological Organization-Global Atmosphere Watch Program (WMO-GAW)/World Ozone and Ultraviolet Radiation Data Centre (WOUDC) [Data]. Retrieved [YYYY-MM-DD], from https://woudc.org. A list of all contributors is available on the website. doi:10.14287/10000004",
    "type": "text/html",
    "href": "https://dx.doi.org/10.14287/10000004"
  }
]
----

==== Properties / Record Creation Date

The `+created+` property is a single date that the WCMP metadata record was created.

include::../requirements/core/REQ_record_creation_date.adoc[]

.Example

[source,json]
----
"properties": {
  ...
  "created": "2021-06-12T23:45:24Z"
  ...
}
----

==== Properties / Record Update Date

The `+updated+` property is the date that the WCMP metadata record was last updated.

include::../recommendations/core/REC_record_update_date.adoc[]

.Example

[source,json]
----
"properties": {
  ...
  "updated": "2022-06-12T18:52:39Z"
  ...
}
----

==== Properties / WMO Data Policy

The `+wmo:dataPolicy+` property is a codelist that identifies the classification of the dataset exchange as described by WMO Unified Data Policy for the International Exchange of Earth System Data (Resolution 1 (Cg-Ext(2021) footnote:[https://library.wmo.int/doc_num.php?explnum_id=11113#page=9]. The codelist values are `+core+` or `+recommended+`.  `+wmo:dataPolicy+` is required if the record describes a dataset.

include::../requirements/core/REQ_data_policy.adoc[]
include::../recommendations/core/PER_data_policy.adoc[]

Licensing and copyright are expressed via the links property (see distribution section), providing access, license and attribution details as required. Conditions on use are essential for the WMO Unified Data Policy, but for transparency and clarification any other conditions should also be indicated.

.Example: Core Data

[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "core"
  ...
}
----

.Example: Recommended Data
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
}
----

.Example: Recommended Data with additional conditions
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
},
"links": [{
  "rel": "license",
  "href": "https://example.org/dataset/license.html",
  "type": "text/html",
  "title": "Dataset license information"
}]
----

It is useful to add provider-specific details to have the most detailed information about data policy and additional conditions.

include::../recommendations/core/REC_data_policy.adoc[]

.Example: Recommended Data with additional conditions and provider-specific details:
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
},
"links": [{
  "rel": "license",
  "href": "https://www.eumetsat.int/eumetsat-data-licensing",
  "type": "text/html",
  "title": "EUMETSAT DATA LICENSING"
}]
----

==== Links and Distribution Information [[links-distribution]]

===== Overview

The `+links+` property describes URLs and APIs for accessing or subscribing to the dataset.

WCMP record links may also provide links to services that implement access control in support of authentication and authorization.  In
secure data use cases, a user needs to be able to detect access-controlled data as part of data discovery and evaluation.

include::../requirements/core/REQ_links.adoc[]
include::../recommendations/core/REC_links.adoc[]

.Example a link object expressing access control using HTTP Basic Authentication for a given data access service

.Example

[source,json]
----
"links": [{
  "rel": "download",
  "type": "application/json",
  "title": "link to WAF endpoint",
  "href": "https://example.org/data/secure-data",
  "security": {
    "type": "http",
    "scheme": "basic",
    "description": "Please contact the data provider for accessing this secured resource."
  }
}]
----

.Example: two link objects providing both search and MQTT subscription information

[source,json]
----
"links": [
  {
    "rel": "search",
    "type": "text/html",
    "title": "WOUDC - Data - Station List",
    "href": "https://woudc.org/data/stations"
  },
  {
    "rel"  : "items",
    "type" : "application/json",
    "title": "WIS2 notification service",
    "href" : "mqtts://example.org",
    "channel": "cache/a/wis2/can/eccc-msc/data/core/weather/surface-based-observations"
  }
]
----

include::../recommendations/core/PER_links.adoc[]

.Example: a link object providing an API capability

[source,json]
----
"links": [
  {
    "rel": "http://www.opengis.net/def/interface/ogcapi-features",
    "type": "application/json",
    "title": "OGC API - Features service",
    "href": "https://example.org/api"
  }
]
----

.Example: a link object providing a browse graphic

[source,json]
----
"links": [
  {
    "rel": "preview",
    "type": "image/png",
    "title": "Browse graphic",
    "href": "https://example.org/path/to/browse.png"
  }
]
----

The `+distribution+` property provides information about the format of the dataset, associated documentation and representative examples of the dataset.

include::../recommendations/core/REC_distribution.adoc[]

.Example: a link object of a WMS service providing API access to images:

[source,json]
----
"links": [{
  "rel": "item",
  "type": "image/png",
  "title": "Eumetview",
  "href": "https://view.eumetsat.int/geoserver/ows?service=WMS&request=GetMap&version=1.3.0&layers=msg_fes:ir108&styles=&format={format}&crs={crs}&bbox={bbox}&width={width}&height={height}",
  "templated": true,
  "variables": {
    "crs": {
      "description": "...",
      "type": "string",
      "enum": [
        "EPSG:4326",
        "EPSG:3857"
      ]
    },
    "bbox": {
      "description": "...",
      "type": "array",
      "items": {
        "type": "number",
        "format": "double"
      },
      "minItems": 4,
      "maxItems": 4
    },
    "width": {
      "description": "...",
      "type": "number",
      "format": "integer",
      "minimum": 600,
      "maximum": 5000
    },
    "height": {
      "description": "...",
      "type": "number",
      "format": "integer",
      "minimum": 600,
      "maximum": 5000
    },
    "format": {
      "description": "...",
      "type": "string",
      "enum": [
        "image/geotiff",
        "image/geotiff8",
        "image/gif",
        "image/jpeg",
        "image/png; mode=8bit"
      ]
    },
    "sampleRequest": "https://view.eumetsat.int/geoserver/ows?service=WMS&request=GetMap&version=1.3.0&layers=msg_fes:ir108&styles=&format=image/jpeg&crs=EPSG:4326&bbox=-77,-77,77,77&width=800&height=800"
  }
}]
----

Additional distribution information is added to allow more comprehensive discovery services. Below is an example of such distribution information.

.Example with the complete distribution information

[source,json]
----
"links": [{
  "rel": "service",
  "type": "text/html",
  "title": "EUMETSAT Datastore",
  "href": "https://data.eumetsat.int/data/map/EO:EUM:DAT:MSG:MSG15-RSS",
  "distribution": {
    "availableFormats": [{
      "name": "native",
      "description": "This is sent in a compressed Submission Information Package (SIP) by default.",
      "numberOfFiles": "288 per day",
      "typicalFilesize": "60 MB",
      "typicalFilename": "MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip",
      "samples": "https://data.eumetsat.int/data/access/MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip",
      "documentation": {
        "rel": "alternate",
        "type": "text/html",
        "title": "SIP documentation and tools",
        "href": "https://www.eumetsat.int/formats#SIP"
      }
    }]
  }
}]
----

WCMP record links may also provide links to services that implement access control in support of authentication and authorization.  In
secure data use cases, a user needs to be able to detect access controlled data as part of data discovery and evaluation.  The
example demonstrates how to express access control using HTTP Basic Authentication for a given data access service.

.Example

[source,json]
----
"links": [{
  "rel": "download",
  "type": "application/json",
  "title": "link to WAF endpoint",
  "href": "https://example.org/data/secure-data",
  "security": {
    "type": "http",
    "scheme": "basic",
    "description": "Please contact the data provider for accessing this secured resource."
  }
}]
----

==== Additional Properties

A WCMP record can be extended as required for organizational purposes by adding properties (of any type) in the
record.  Additional properties do not break compliance to WCMP.

include::../recommendations/core/PER_additional_properties.adoc[]

.Example

[source,json]
----
"properties": {
  ...
  "approvalStatus": "approved"
  "_comment": {
    "validationErrors": [
      "error 1",
      "error 2"
    ]
  }
  ...
}
----

