== Scope

This document defines the content, structure, and encoding of discovery metadata published
as part of the WIS2 Global Discovery Catalogue (GDC).

The WMO Core Metadata Profile (WCMP) standard defined herein is an extension of the International Standard _OGC API - Records - Part 1: Core_.

WCMP discovery metadata records shall be encoded as GeoJSON as defined in _OGC API - Records - Part 1: Core_.

The primary purpose of WCMP is to describe **datasets**.  While WCMP can describe any
resource (datasets, APIs and data reduction services, processes, analytics, etc.), the key
component for international data exchange is data.  Services and APIs operating on resources
may be represented as part of their own metadata or associated through WCMP links.

WCMP discovery metadata record provides descriptions at the granularity level of a dataset.  Station, instrument and observation metadata are supported by the _WIGOS Metadata Standard (WMO-No. 1192)_ footnote:[https://library.wmo.int/doc_num.php?explnum_id=10109].

This specification defines the conformance requirements for the WMO Core Metadata Profile.  Annex A defines the abstract test suite. Annex B provides normative information on schemas.  Annex C provides informative examples.  Annex D provides normative information on codelists.
