== Conventions
This section provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of JSON schema, or special notes regarding how to read the document.

=== Identifiers
The normative provisions in this Standard are denoted by the URI:

http://wis.wmo.int/spec/wcmp/2.0

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Examples

Examples provided in this specification are encoded as GeoJSON.

Complete examples can be found at https://schemas.wmo.int/wcmp/2.0/examples

=== Schemas

The WCMP 2.0 schema can be found at https://schemas.wmo.int/wcmp/2.0/wcmpRecordGeoJSON.yaml 

=== Schema representation

JSON Schema footnote:[https://json-schema.org] objects are used throughout this specificiation to define the structure
of metadata records. These schema / objects are also typically represented using YAML footnote:[https://en.wikipedia.org/wiki/YAML].
YAML is a superset of JSON, and in this specification are regarded as equivalent.

Metadata record instances are always defined as JSON.

=== Use of HTTPS

For simplicity, this document in general only refers to the HTTP protocol. This is not meant to exclude the use of HTTPS and simply is a shorthand notation for "HTTP or HTTPS." In fact, most servers are expected to use HTTPS, not HTTP.
