== The WMO Core Metadata Profile Record

A WCMP record provides descriptive information about a dataset made available
through WIS 2.0.

=== Conformance Class Core

The WCMP Core Conformance Class provides requirements to articulate the required elements
of a WCMP discovery metadata record.

include::../requirements/requirements_class_core.adoc[]

==== Validation

The WCMP record schema is based on the schema defined as part of OGC API - Records - Part 1:
Core: Requirements Class: Record Core and the associated information model.  WCMP records which
are valid to WCMP are therefore valid to the OGC API - Records record schema.

include::../requirements/core/REQ_validation.adoc[]

==== Identifier

A WCMP record utilizes the OARec `+id+` property to provide a unique identifier
to a dataset collection.  A record identifier is essential for querying and identifying
records within the GDC.

include::../requirements/core/REQ_identifier.adoc[]

==== Conformance

A WCMP record leverages the OGC API `+conformsTo+` property to identify the conformance classes
that apply to the record.  WCMP conformance identification is valuable for content/version
detection and handling.

include::../requirements/core/REQ_conformance.adoc[]

==== Type

WCMP records can provide descriptive information about a number of different resource types, such as
dataset or services.

include::../requirements/core/REQ_type.adoc[]

==== Title

A WCMP record's `+properties.title+` property is a human-readable name given to a given dataset collection.

include::../requirements/core/REQ_title.adoc[]

==== Description

A WCMP record can have a `+properties.description+` property, which is a free-text summary description of the
resource the provider wishes to make discoverable. TODO: this is now a SHALL

include::../requirements/core/REQ_description.adoc[]

==== Themes and Topic Hierarchy

A WCMP record has a `+properties.themes+` property, which is a knowledge organization system used to classify
the data that the record is describing.  A WCMP can have one or more themes.  The WIS Topic Hierarchy is put
forth as a specific theme/concept.

include::../requirements/core/REQ_themes_topic_hierarchy.adoc[]

TODO: should we add a RECOMMENDATION for keywords?

==== Providers

A WCMP record can be one or more providers as part of the `+properties.providers+` property.  These elements
provide contact information based on the role of the provider.

include::../requirements/core/REQ_providers.adoc[]

==== Record Creation Date

A WCMP record has a `+properties.recordCreated+` property, which describes the date that the record was created.

include::../requirements/core/REQ_record_creation_date.adoc[]

==== Record Update Date

A WCMP record has a `+properties.recordUpdated+` property, which describes the date that the record was changed.

include::../requirements/core/REQ_record_update_date.adoc[]
