== The WMO Core Metadata Profile Record

A WCMP record provides descriptive information about a dataset made available through WIS2.

=== Requirements Class "Core"

==== Overview

The WCMP Core Requirements Class provides requirements for a WCMP discovery metadata record.

include::../requirements/requirements_class_core.adoc[]


The table below provides an overview of the set of properties that may be included in a WCMP record.


.WCMP record core properties
|===
|Property|Requirement|Description

|``id``
|**required**
|A unique identifier of the dataset (see <<_identifier>>)

|``type``
|**required**
|A fixed value denoting the WCMP record as a GeoJSON ``Feature`` (see <<_validation>>)

|``conformsTo``
|**required**
|The version of WCMP associated that the record conforms to (see <<_conformance_2>>)

|``properties.type``
|**required**
|The resource type described by the WCMP record (see <<_properties_type>>)

|``properties.title``
|**required**
|A human-readable name of the dataset (see <<_properties_title>>)

|``properties.description``
|**required**
|A free-text summary description of the dataset (see <<_properties_description>>)

|``properties.keywords``
|optional
|Keywords, tags or key phrases (see <<_properties_keywords>>)

|``properties.themes``
|**required**
|Classifiers, categories and controlled vocabularies (see <<_properties_themes>>)

|``geometry``
|**required**
|Geospatial location associated with the dataset, in a geographic coordinate reference system (see <<_geospatial_extent>>)

|``time``
|**required**
|Temporal extent associated with the dataset (see <<_temporal_extent>>)

|``additionalExtents.spatial``
|optional
|Additional geospatial extents in other coordinate reference systems (see <<_additional_geospatial_extents>>)

|``additionalExtents.temporal``
|optional
|Additional time instants or periods (see <<_additional_temporal_extents>>)

|``properties.contacts``
|**required**
|Contact information for the dataset (see <<_properties_contacts>>)

|``properties.version``
|optional
|Version or edition of the dataset (see <<_properties_version>>)

|``properties.externalIds``
|optional
|Persistent identifiers or handles for the dataset (see <<_properties_persistent_identifiers>>)

|``properties.created``
|**required**
|The date that the WCMP record was created (see <<_properties_record_creation_date>>)

|``properties.updated``
|optional
|The date that the WCMP record was updated (see <<_properties_record_update_date>>)

|``properties.status``
|optional
|The operational status of the dataset (see <<_properties_status>>)

|``properties.wmo:dataPolicy``
|**conditional**
|Classification code of ``core`` or ``recommended`` based on the WMO Unified Data Policyfootnote:[https://library.wmo.int/idurl/4/58009].  **Required** for datasets (see <<_properties_wmo_data_policy>>)

|``properties.rights``
|optional
|A statement that concerns all rights not addressed by the license such as a copyright statement. (see <<_properties_wmo_data_policy>>)

|``links``
|**required**
|Online linkages to data retrieval or additional resources associated with the dataset (see <<links-distribution>>)

|``linkTemplates``
|optional
|Online link templates for dynamic / API access (see <<_templated_links>>)

|``properties.*``
|optional
|Additional properties as needed (see <<_additional_properties>>)

|===

==== Validation

The WCMP record schema is based on  _OGC API - Records - Part 1: Core: Requirements Class: Record Core_ schema and the associated information model.  WCMP records compliant with WCMP schema are therefore compliant with the _OGC API - Records_ record schema.

include::../requirements/core/REQ_validation.adoc[]

==== Identifier

The `+id+` property is a unique identifier
of the dataset.  A record identifier is essential for querying and identifying records within the GDC.

.Example

[source,json]
----
"id": "urn:wmo:md:ca-eccc-msc:observations.swob"
----

include::../requirements/core/REQ_identifier.adoc[]
include::../recommendations/core/PER_identifier.adoc[]

==== Conformance

The `+conformsTo+` property to identifies the version ofthe WCMP standard that the metadata record conforms to. Conformance identification is valuable for version
detection and handling of content.

.Example

[source,json]
----
"conformsTo": [
  "http://wis.wmo.int/spec/wcmp/2/conf/core"
]
----

include::../requirements/core/REQ_conformance.adoc[]

==== Properties / Type

The `+type+` property identifies the type of resource that the metadata record describes using values from the resource type codelist. While most metadata records will be set to `dataset`,
WCMP can also describe additional resources, such as services and processes.

A **dataset** is the primary granularity of a WCMP record describing a collection of data granules.

A **service** is an API or Web service providing a discovery, visualization, or access mechanism that operates on data.

A **process** is a workflow or execution to provide custom functionality to calculate a given output or product.

.Example:

[source,json]
----
"properties": {
  ...
  "type": "dataset"
  ...
}
----

include::../requirements/core/REQ_type.adoc[]

==== Properties / Title

The `+title+` property is a human-readable name of the dataset.

.Example

[source,json]
----
"properties": {
  ...
  "title": "Surface weather observations"
  ...
}
----

include::../requirements/core/REQ_title.adoc[]

==== Properties / Description

The `+description+` property is a free-text summary of the dataset.

.Example

[source,json]
----
"properties": {
  ...
  "description": "Surface observations measured at the automatic and manual stations of the Environment and Climate Change Canada and partners networks, either for a single station or for the stations of specific provinces and territories (last 30 days)."
  ...
}
----

include::../requirements/core/REQ_description.adoc[]

==== Properties / Keywords

The `+keywords+` property is a list of keywords, tags or specific phrases associated with the resource, but are not referenced to a particular vocabulary or knowledge organization system.

.Example

[source,json]
----
"properties": {
  ...
  "keywords": [
    "surface",
    "observations",
    "weather",
    "real-time"
  ]
  ...
}
----

include::../recommendations/core/REC_keywords.adoc[]

==== Properties / Themes

The `+themes+` property is a list of concepts that are referenced to a vocabulary or knowledge organization system used to classify the resource.  

A theme's `+scheme+` property provides a remote reference to a controlled vocabulary, codelist or knowledge organization system.

A concept's `+id+` provides an identifier for the given concept, as well as optional `+title+`, `+description+` and `+url+` properties to further describe the concept as desired.

A concept's optional `+url+` property can provide a remote reference to a given concept (for example, to an online ontology or code registry).

A WCMP metadata record can have one or more themes.

.Examples
[source,json]
----
"properties": {
  ...
  "themes": [
    {
      "concepts": [
        {
          "id": "0-0-0",
          "title": "Temperature",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/0-0-0"
        },
        {
          "id": "0-1-1",
          "title": "Relative humidity",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/0-1-1"
        },
        {
          "id": "0-2-2",
          "title": "u-component of Wind",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/0-2-2"
        },
        {
          "id": "0-2-3",
          "title": "v-component of Wind",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/0-2-3"
        }
      ],
      "scheme": "http://codes.wmo.int/grib2/codeflag/4.2"
    }
  ]
  ...
}
----

[source,json]
----
"themes": [
  {
    "concepts": [
      {
        "id": "001",
        "title": "Temperature/air temperature",
        "kurl": "http://codes.wmo.int/bufr4/b/12/001"
      },
      {
        "id": "003",
        "title": "Dewpoint temperature",
        "url": "http://codes.wmo.int/bufr4/b/12/003"
      }
    ],
    "scheme": "http://codes.wmo.int/bufr4/b"
  }
]
----

[source,json]
----
"properties": {
  ...
  "themes": [
    {
      "concepts": [{
        "id": "weather",
        "title": "Weather",
        "url": "http://codes.wmo.int/wis/topic-hierarchy/earth-system-discipline/weather"
      }],
      "scheme": "http://codes.wmo.int/wis/topic-hierarchy/earth-system-discipline"
    }
  ]
  ...
}
----

include::../requirements/core/REQ_themes.adoc[]
include::../requirements/core/REQ_themes_wis2_global_service.adoc[]
include::../recommendations/core/REC_granularity.adoc[]
include::../recommendations/core/PER_themes.adoc[]

==== Geospatial and temporal extents

===== Geospatial extent

The `+geometry+` property is the general bounding spatial extent of the dataset in the geographic coordinate system.  
Geospatial bounding extents provide a useful indicator of the location of the dataset to facilitate search and map displays in the GDC.

.Examples

[source,json]
----
"geometry": {
  "type": "Polygon",
  "coordinates": [[
    [-142.23, 28.03],
    [-142.23, 82.56],
    [-52.16, 82.56],
    [-52.16, 28.03],
    [-142.23, 28.03]
  ]]
}
----

[source,json]
----
"geometry": {
  "type": "Point",
  "coordinates": [-79.38, 43.65]
}
----

[source,json]
----
"geometry": null
----

include::../requirements/core/REQ_extent_geospatial.adoc[]
include::../recommendations/core/REC_extent_geospatial_point.adoc[]
include::../recommendations/core/REC_extent_geospatial_precision.adoc[]
include::../recommendations/core/REC_extent_geospatial_wis2_global_service.adoc[]

===== Additional geospatial extents

The `+additionalExtents.spatial+` property is for other geospatial extents associated with the dataset. For example, it may be useful for non-geographic data or for describing multiple sub-areas of a dataset.
The `+additionalExtents.spatial.bbox+` property
provides the ability to list one to many minimum bounding geometries for a given dataset, where:

* minx is the westernmost coordinate of the limit of the dataset extent, expressed in longitude decimal degrees as a
signed number between -180 and 180, less than or equal to maxx.
* miny is the southernmost coordinate of the limit of the dataset extent, expressed in latitude decimal degrees as a
signed number between -90 and 90, less than or equal to maxy.
* maxx is the easternmost coordinate of the limit of the dataset extent, expressed in longitude decimal degrees as a
signed number between -180 and 180, greater than or equal to minx.
* maxy is the northernmost coordinate of the limit of the dataset extent, expressed in latitude decimal degrees as a
signed number between -90 and 90, greater than or equal to miny.

This property also facilitates catalogue searches with geospatial predicate (within extent, etc.).

.Example

[source,json]
----
"additionalExtents": {
  "spatial": {
    "bbox": [
      [-142, 42, -52, 84]
    ],
    "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
  }
}
----

include::../recommendations/core/PER_extent_geospatial.adoc[]

===== Temporal extent

The `+time+` property describes the general bounding extent of the dataset and the temporal resolution. 

Temporal extents provide a useful indicator of the date and time period of the dataset and facilitates temporal searching in the GDC. 

In addition the temporal resolution provides a useful indicator of the data update frequency (for example, for real-time datasets). If only times are given for the interval, it is implicitly assumed that those are recurring every day.

In cases where no time indication can be derived, it is applicable to state the value of `+null+`.

.Examples

[source,json]
----
"time": {
  "date": "2021-10-30"
}
----

[source,json]
----
"time": {
  "timestamp": "2021-10-30T11:11:11Z"
}
----

[source,json]
----
"time": {
  "interval" : ["2020-10-30", "2021-10-30"],
  "resolution": "P1D"
}
----

[source,json]
----
"time": {
  "interval" : ["T00Z", "T23Z"],
  "resolution": "PT1H"
}
----

[source,json]
----
"time": {
  "interval": ["2018-04-22", ".."],
}
----

[source,json]
----
"time": null
----

To ensure clarity, an additional human-readable explanation is given in the `+properties.description+`.
Further time-related characteristics (e.g. frequency of modifications, available data, etc.) should be added in `+properties.themes+`.

Some cases might be more complex due to the product's characteristics.
If necessary, further granularity can be indicated by the `+additionalExtents.temporal+` property (see <<_additional_temporal_extents>>).

.Example: Complex time indication

[source,json]
----
"time": {
  "interval" : ["2018-04-22", ".."]
},
"additionalExtents": {
  "temporal": {
    "interval": [
      [
        "T00Z",
        "PT180H"
      ],
      [
        "T12Z",
        "PT180H"
      ]
    ],
    "resolution": "PT6H",
    "trs": "http://www.opengis.net/def/trs/ISO-8601"
  }
}
...
"properties": {
  ...
  "description": "ICON-EPS 0.5\u00b0 x 0.5\u00b0 regular lat/lon grid, up to +180h every 6h, runs 00/12 UTC, various parameter, various level, various threshold",
  "themes": [
    {
      "concepts": [
        {"id": "continual"}
      ],
      "scheme": "https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_FrequencyCode"
    }
  ]
}
----

include::../requirements/core/REQ_extent_temporal.adoc[]
include::../recommendations/core/REC_extent_temporal.adoc[]
include::../recommendations/core/PER_extent_temporal_service.adoc[]

===== Additional temporal extents

The `+additionalExtents.temporal+` property is for describing other temporal extents associated with the dataset. For example, it may be useful to represent multiple time instances or to identify other temporal reference systems. 
Temporal extents can be fully bound or open in either direction.  An `+additionalExtents.temporal.resolution+` property is able express the temporal granularity at which a given dataset's data is measured, generated, or reported.

.Example

[source,json]
----
"additionalExtents": {
  "temporal": {
    "interval": [
      [
        "T00Z",
        "PT180H"
      ],
      [
        "T12Z",
        "PT180H"
      ]
    ],
    "resolution": "PT6H",
    "trs": "http://www.opengis.net/def/trs/ISO-8601"
  }
}
----

include::../recommendations/core/PER_extent_temporal.adoc[]

==== Properties / Contacts

The `+contacts+` property is the information associated with one or more responsible parties of the resource.

.Examples

[source,json]
----
"properties": {
  ...
  "contacts": [{
    "identifier": "ECCC",
    "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
    "name": "National Inquiry Response Team",
    "phones": [{
      "value": "+18199972800"
    }],
    "emails": [{
      "value":"enviroinfo@ec.gc.ca"
    }],
    "addresses": [{
      "deliveryPoint": [ "77 Westmorland Street, suite 260" ],
      "city": "Fredericton",
      "administrativeArea": "NB",
      "postalCode": "E3B 6Z4",
      "country": "Canada"
    }],
    "links": [{
      "href": "https://example.org/about",
      "rel": "about",
      "type": "text/html"
    }],
    "contactInstructions": "email",
    "roles": ["producer", "host"]
  }]
  ...
}
----

A contact can also be specified by using a URL.

[source,json]
----
"properties": {
  ...
  "contacts": [{
    "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
    "links": [{
      "href": "https://example.org/about",
      "rel": "about",
      "type": "text/html"
    }],
    "roles": ["producer"]
  }]
}
----

include::../requirements/core/REQ_contacts.adoc[]
include::../recommendations/core/PER_contacts.adoc[]

==== Properties / Version

The `+version+` property is the version or edition of the dataset. Datasets may be versioned by an organization, for example, the version of an NWP model or a processing chain/workflow, and data providers can make this information available when there are multiple versions of a dataset over time.

.Example

[source,json]
----
"properties": {
  ...
  "version": "0.1.0"
  ...
}
----

include::../recommendations/core/PER_version.adoc[]

==== Properties / Persistent identifiers

The `+externalIds+` property is a persistent (or handle) identifier used to provide a long lasting reference to a digital resource.  Persistent identifiers are commonly used for scientific publications and datasets.

Examples of persistent identifiers include, but are not limited to:

* Digital Object Identifiers (DOI)footnote:[https://doi.org]
* Archival Resource Key (ARK)footnote:[https://arks.org]
* Handlefootnote:[https://handle.net]

.Example

[source,json]
----
"properties": {
  ...
  "externalIds": [{
    "scheme": "https://doi.org",
    "value": "10.14287/10000001"
  }, {
    "scheme": "https://handle.net",
    "value": "2381/12775"
  }, {
    "scheme": "https://arks.org",
    "value": "ark:/13030/tf5p30086k"
  }]
  ...
}
----

.Example: Online citation

[source,json]
----
"links": [
  {
    "rel": "cite-as",
    "title": "Cite as: WMO/GAW Ozone Monitoring Community, World Meteorological Organization-Global Atmosphere Watch Program (WMO-GAW)/World Ozone and Ultraviolet Radiation Data Centre (WOUDC) [Data]. Retrieved [YYYY-MM-DD], from https://woudc.org. A list of all contributors is available on the website. doi:10.14287/10000004",
    "type": "text/html",
    "href": "https://dx.doi.org/10.14287/10000004"
  }
]
----

include::../recommendations/core/REC_pids.adoc[]
include::../recommendations/core/PER_pids.adoc[]

==== Properties / Record creation date

The `+created+` property is a single date that the WCMP metadata record was created. Note, that this date is not the start or end time of a given dataset.  See <<_temporal_extent>> for more information on defining dataset temporal extents.

.Example

[source,json]
----
"properties": {
  ...
  "created": "2021-06-12T23:45:24Z"
  ...
}
----

include::../requirements/core/REQ_record_creation_date.adoc[]

==== Properties / Record update date

The `+updated+` property is the date that the WCMP metadata record was last updated. Note, that this date is not the start or end time of a given dataset.  See <<_temporal_extent>> for more information on defining dataset temporal extents.

.Example

[source,json]
----
"properties": {
  ...
  "updated": "2022-06-12T18:52:39Z"
  ...
}
----

include::../recommendations/core/REC_record_update_date.adoc[]

==== Properties / Status

The `+status+` property identifies the lifecycle of a given dataset.  See Annex D for possible codelists to use when encoding this property.

[source,json]
----
"properties": {
  "status": {
    "id": "operational",
    "title": "dataset is in 24/7 operation",
    "url": "https://example.org/my-vocab"
  }
}
----

include::../recommendations/core/REC_status.adoc[]

==== Properties / WMO data policy

The `+wmo:dataPolicy+` property is a codelist that identifies the classification of the dataset exchange as described by WMO Unified Data Policyfootnote:[https://library.wmo.int/idurl/4/58009]
for the international exchange of Earth system data. The codelist values are `+core+` or `+recommended+`.  The `+wmo:dataPolicy+` property is required if the metadata record describes a dataset.

Licensing and copyright are expressed via the `+links+` property (see distribution section), providing access, license and attribution details as required. Conditions on use of the data should be indicated for transparency and clarification.

.Example: Core data

[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "core"
  ...
}
----

.Example: Recommended data
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
}
----

It is useful to add provider-specific details to have the most detailed information about data policy and additional conditions.

.Example: Recommended data with additional conditions and provider-specific details:
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
},
"links": [{
  "rel": "license",
  "href": "https://example.org/license",
  "type": "text/html",
  "title": "EUMETSAT DATA LICENSING"
}]
----

.Example: Recommended data for data put into the public domain:
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
},
"links": [{
  "rel": "license",
  "href": "https://creativecommons.org/publicdomain/zero/1.0/",
  "type": "text/html",
  "title": "CC0 1.0 Deed | CC0 1.0 Universal | Creative Commons"
}]
----

To express rights not address by a license, the `+rights+` property can be used as follows:

.Example: Rights
[source,json]
----
"properties": {
 ...
 "rights": "Users are granted free and unrestricted access to this data, without charge and with no conditions on use. Users are requested to attribute the producer of this data. WMO Unified Data Policy (Resolution 1 (Cg-Ext 2021))"
 ...
}
----

include::../requirements/core/REQ_data_policy.adoc[]
include::../recommendations/core/REC_data_policy.adoc[]
include::../recommendations/core/PER_data_policy.adoc[]

==== Links and distribution information [[links-distribution]]

===== Overview

The `+links+` property describes URLs and APIs for accessing the dataset or for subscribing to dataset notifications. Links are the primary mechanism for interacting with the data, and provide an "actionable" workflow to enhance and improve the user experience with "less clicks" for subscriptions and downloads.

The `+links+` property may also describe URLs for related documentation, related data, or visual images of the dataset.

The table below provides an overview of the properties of a link object.

.Link properties
|===
|Property|Requirement|Description

|``href``
|**required**
|The link destination or target, or URL

|``rel``
|**optional**
|The relationship that the link bears in the context of the WCMP record.  This is a controlled vocabulary defined
 by IANA link relationsfootnote:[https://www.iana.org/assignments/link-relations/link-relations.xhtml] or WCMP
 defined extensionsfootnote:[https://codes.wmo.int/wis/link-type] (see <<_link_relation_selection>>)

|``type``
|**optional**
|The media (or MIME) type of the format of the link

|``hreflang``
|**optional**
|The language of the content in the link

|``title``
|**optional**
|A human-readable name for the link (can be used for display on search / discovery web portals)

|``channel``
|**conditional**
|For data made available via MQTT, the topic to which a user may subscribe to for notifications and access

|``security``
|**optional**
|For access controlled data, a description of the access control mechanism applied (see <<_access_control>>)

|``distribution``
|**optional**
|Value added information about the link to further assist the user (additional document, typical file size, etc.) (see <<_distribution_information>>)

|===

For recommended data, the ``links`` property may also provide links to services that implement access control in support of authentication and authorization.  In secure data use cases, a user needs to be able to detect access-controlled data as part of data discovery and evaluation.

.Example a link object expressing access control using HTTP Basic Authentication for a given data access service

.Example Access controlled link

[source,json]
----
"links": [{
  "rel": "data",
  "type": "application/json",
  "title": "link to WAF endpoint",
  "href": "https://example.org/data/secure-data",
  "security": {
    "default": {
      "type": "http",
      "scheme": "basic",
      "description": "Please contact the data provider for accessing this secured resource."
    }
  }
}]
----

.Example: two link objects providing both search and MQTT subscription information

[source,json]
----
"links": [
  {
    "rel": "search",
    "type": "text/html",
    "title": "WOUDC - Data - Station List",
    "href": "https://example.org/data/stations"
  },
  {
    "rel"  : "items",
    "type" : "application/json",
    "title": "WIS2 notification service",
    "href" : "mqtts://example.org",
    "channel": "cache/a/wis2/ca-eccc-msc/data/core/weather/surface-based-observations"
  }
]
----

.Example: a link object providing an API capability

[source,json]
----
"links": [
  {
    "rel": "service",
    "type": "application/json",
    "title": "OGC API - Features service",
    "href": "https://example.org/api"
  }
]
----

.Example: a link object providing a browse graphic

[source,json]
----
"links": [
  {
    "rel": "preview",
    "type": "image/png",
    "title": "Browse graphic",
    "href": "https://example.org/path/to/browse.png"
  }
]
----

===== Templated links

Templated links allow for specifying a pattern of a link in support API interaction (where parameter values are variable).

.Example: a templated link object of a WMS service providing API access to images:
[source,json]
----
"linkTemplates": [{
  "rel": "item",
  "type": "image/png",
  "title": "Eumetview",
  "uriTemplate": "https://example.org/geoserver/ows?service=WMS&request=GetMap&version=1.3.0&layers=msg_fes:ir108&styles=&format={format}&crs={crs}&bbox={bbox}&width={width}&height={height}",
  "variables": {
    "crs": {
      "description": "...",
      "type": "string",
      "enum": [
        "EPSG:4326",
        "EPSG:3857"
      ]
    },
    "bbox": {
      "description": "...",
      "type": "array",
      "items": {
        "type": "number",
        "format": "double"
      },
      "minItems": 4,
      "maxItems": 4
    },
    "width": {
      "description": "...",
      "type": "number",
      "format": "integer",
      "minimum": 600,
      "maximum": 5000
    },
    "height": {
      "description": "...",
      "type": "number",
      "format": "integer",
      "minimum": 600,
      "maximum": 5000
    },
    "format": {
      "description": "...",
      "type": "string",
      "enum": [
        "image/geotiff",
        "image/geotiff8",
        "image/gif",
        "image/jpeg",
        "image/png; mode=8bit"
      ]
    },
    "sampleRequest": "https://example.org/geoserver/ows?service=WMS&request=GetMap&version=1.3.0&layers=msg_fes:ir108&styles=&format=image/jpeg&crs=EPSG:4326&bbox=-77,-77,77,77&width=800&height=800"
  }
}]
----

include::../requirements/core/REQ_links.adoc[]
include::../recommendations/core/REC_links.adoc[]
include::../recommendations/core/PER_links.adoc[]

===== Distribution information

The `+distribution+` property provides information about the format of the dataset, associated documentation and representative examples of the dataset.

Additional distribution information is added to allow more comprehensive discovery services. Below is an example of such distribution information.

.Example with the complete distribution information

[source,json]
----
"links": [{
  "rel": "search",
  "type": "text/html",
  "title": "EUMETSAT Datastore",
  "href": "https://example.org/data/map/EO:EUM:DAT:MSG:MSG15-RSS",
  "distribution": {
    "availableFormats": [{
      "name": "native",
      "description": "This is sent in a compressed Submission Information Package (SIP) by default.",
      "numberOfFiles": "288 per day",
      "typicalFilesize": "60 MB",
      "typicalFilename": "MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip",
      "samples": { 
        "href": "https://example.org/data/access/MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip" 
      },
      "documentation": [{
        "rel": "alternate",
        "type": "text/html",
        "title": "SIP documentation and tools",
        "href": "https://www.eumetsat.int/formats#SIP"
      }]
    }]
  }
}]
----

include::../recommendations/core/REC_distribution.adoc[]

===== Access control

WCMP record links may also provide links to services that implement access control in support of authentication and authorization.  In
secure data use cases, a user needs to be able to detect access controlled data as part of data discovery and evaluation.  The
example demonstrates how to express access control using HTTP Basic Authentication for a given data access service.

.Example

[source,json]
----
"links": [{
  "rel": "data",
  "type": "application/json",
  "title": "link to WAF endpoint",
  "href": "https://example.org/data/secure-data",
  "security": {
    "default": {
      "type": "http",
      "scheme": "basic",
      "description": "Please contact the data provider for accessing this secured resource."
    }
  }
}]
----

===== Link relation selection

Link relations are very important and provide valuable context to help clarify the semantics of a given link or URL.

The table below provides guidance on which link relation to use to identify common types of
links to data and services.

.Link relation selection
|===
|Link type|Link relation (`rel=`)

|Online data archive
|`archives`

|Online documentation
|`about`

|OpenAPI endpoint (e.g. JSON or YAML)
|`service-desc`

|OpenAPI endpoint in HTML (e.g. Swagger, ReDoc)
|`service-doc`

|OGC WMS, WFS, WCS, CSW, WPS Capabilities
|`service-desc`

|A single link providing numerous data granules
|`items`

|A link providing a single data granule
|`item`

|A link to numerous stations that the dataset is based on
|`stations`

|A link to a single station that the dataset is based on
|`station`

|citation
|`cite-as`

|A search portal or web application
|`search`

|A zipfile of data, or bulk download
|`enclosure`

|A browse graphic of a dataset
|`preview`

|An OGC API endpoint providing a collection description
|`collection`

|===

==== Additional properties

A WCMP record can be extended as required for organizational purposes by adding properties (of any type) in the
record.  Additional properties do not break compliance to WCMP.

.Example

[source,json]
----
"properties": {
  ...
  "approvalStatus": "approved"
  "_comment": {
    "validationErrors": [
      "error 1",
      "error 2"
    ]
  }
  ...
}
----

include::../recommendations/core/PER_additional_properties.adoc[]
