== WMO Core Metadata Profile (Version 2)

Note: This section of this working draft document is the same as Appendix F in the https://library.wmo.int/idurl/4/68731[_Manual on the WMO Information System_] (WMO-No. 1060), Volume II as approved by EC-78.

WMO Core Metadata Profile (WCMP) is an extension of the OGC API – Features standard and shall be encoded in GeoJSON. The normative provisions in WCMP (version 2) are denoted by the base URI (``http://wis.wmo.int/spec/wcmp/2``) and requirements are denoted by partial URIs relative to this base. Property names, values and examples are represented with ``shaded text`` in this document.

:sectnums!:
=== 1. Requirements Class "Core"

include::../requirements/requirements_class_core.adoc[]

==== 1.1 Overview

The table below provides an overview of the set of properties that may be included in a WCMP record.

.Table. WCMP record core properties
|===
|Property|Requirement|Description

|``id``
|**Required**
|A unique identifier of the dataset (see <<_1_4_identifier>>)

|``type``
|**Required**
|A fixed value denoting the WCMP record as a GeoJSON ``Feature`` (see <<_1_3_validation>>)

|``conformsTo``
|**Required**
|The version of WCMP associated to which the record conforms (see <<_1_5_conformance>>)

|``properties.type``
|**Required**
|The resource type described by the WCMP record (see <<_1_6_properties_type>>)

|``properties.title``
|**Required**
|A human-readable name of the dataset (see <<_1_7_properties_title>>)

|``properties.description``
|**Required**
|A free-text summary description of the dataset (see <<_1_8_properties_description>>)

|``properties.keywords``
|Optional
|Keywords, tags or key phrases (see <<_1_9_properties_keywords>>)

|``properties.themes``
|**Required**
|Classifiers, categories and controlled vocabularies (see <<_1_10_properties_themes>>)

|``geometry``
|**Required**
|Geospatial location associated with the dataset, in a geographic coordinate reference system (see <<_1_11_1_geospatial_extent>>)

|``time``
|**Required**
|Temporal extent associated with the dataset (see <<_1_11_3_temporal_extent>>)

|``additionalExtents.spatial``
|Optional
|Additional geospatial extents in other coordinate reference systems (see <<_1_11_2_additional_geospatial_extents>>)

|``additionalExtents.temporal``
|Optional
|Additional time instants or periods (see <<_1_11_4_additional_temporal_extents>>)

|``properties.contacts``
|**Required**
|Contact information for the dataset (see <<_1_12_properties_contacts>>)

|``properties.version``
|Optional
|Version or edition of the dataset (see <<_1_13_properties_version>>)

|``properties.externalIds``
|Optional
|Persistent identifiers or handles for the dataset (see <<_1_14_properties_persistent_identifiers>>)

|``properties.created``
|**Required**
|The date that the WCMP record was created (see <<_1_15_properties_record_creation_date>>)

|``properties.updated``
|Optional
|The date that the WCMP record was updated (see <<_1_16_properties_record_update_date>>)

|``properties.status``
|Optional
|The operational status of the dataset (see <<_1_17_properties_status>>)

|``properties.wmo:dataPolicy``
|**Conditional**
|Classification code of ``core`` or ``recommended``, based on the WMO Unified Data Policy (Resolution 1 (Cg-Ext(2021)))footnote:[Resolution 1 (Cg-Ext(2021)) – WMO Unified Policy for the International Exchange of Earth System Data (World Meteorological Congress: Abridged Final Report of the Extraordinary Session (WMO-No. 1281))].  **Required** for datasets (see <<_1_18_properties_wmo_data_policy>>)

|``properties.rights``
|Optional
|A statement that concerns all rights not addressed by the license, such as a copyright statement
(see <<_1_18_properties_wmo_data_policy>>)

|``links``
|**Required**
|Online linkages to data retrieval or additional resources associated with the dataset (see <<_1_19_links_and_distribution_information>>)


|``linkTemplates``
|Optional
|Online link templates for dynamic/API access (see <<_1_19_2_templated_links>>)

|``properties.*``
|Optional
|Additional properties as needed (see <<_1_20_additional_properties>>)

|===

==== 1.2. WMO Core Metadata Profile record representation

WCMP record can be represented in various ways internally, in WIS systems and software tools, but its external representation is GeoJSON.

include::../recommendations/core/REC_media_type.adoc[]

==== 1.3 Validation

The WCMP record schema is based on the Requirements Class "Record Core" of OGC API – Records – Part 1: Core schema and the associated information model. WCMP records compliant with the WCMP schema are therefore compliant with the OGC API – Records record schema.

include::../requirements/core/REQ_validation.adoc[]

==== 1.4 Identifier

The `+id+` property is a unique identifier
of the dataset.  A record identifier is essential for querying and identifying records within the Global Discovery Catalogue (GDC).

.Example

[source,json]
----
"id": "urn:wmo:md:ca-eccc-msc:observations.swob"
----

include::../requirements/core/REQ_identifier.adoc[]
include::../recommendations/core/PER_identifier.adoc[]

==== 1.5 Conformance

The `+conformsTo+` property identifies the version of the WCMP standard to which the metadata record conforms. Conformance identification is valuable for version
detection and handling of content.

.Example

[source,json]
----
"conformsTo": [
  "http://wis.wmo.int/spec/wcmp/2/conf/core"
]
----

include::../requirements/core/REQ_conformance.adoc[]

==== 1.6 Properties / Type

The `+type+` property identifies the type of resource that the metadata record describes, using values from the resource type code list in the WMO Codes Registry. While most metadata records will be set to `dataset`,
a WCMP record can also describe additional resources, such as services and processes.

A **dataset** is the primary granularity of a WCMP record describing a collection of data granules.

A **service** is an API or web service providing a discovery, visualization or access mechanism that operates on data.

A **process** is a workflow or execution to provide custom functionality to calculate a given output or product.

.Example:

[source,json]
----
"properties": {
  ...
  "type": "dataset"
  ...
}
----

include::../requirements/core/REQ_type.adoc[]

==== 1.7 Properties / Title

The `+title+` property is a human-readable name of the dataset.

.Example:

[source,json]
----
"properties": {
  ...
  "title": "Surface weather observations"
  ...
}
----

include::../requirements/core/REQ_title.adoc[]

==== 1.8 Properties / Description

The `+description+` property is a free-text summary of the dataset.

.Example

[source,json]
----
"properties": {
  ...
  "description": "Surface observations measured at the automatic and manual stations of the Environment and Climate Change Canada and partners networks, either for a single station or for the stations of specific provinces and territories (last 30 days)."
  ...
}
----

include::../requirements/core/REQ_description.adoc[]

==== 1.9 Properties / Keywords

The `+keywords+` property is a list of keywords, tags or specific phrases associated with the resource, but are not referenced to a particular vocabulary or knowledge organization system.

.Example:

[source,json]
----
"properties": {
  ...
  "keywords": [
    "surface",
    "observations",
    "weather",
    "real-time"
  ]
  ...
}
----

include::../recommendations/core/REC_keywords.adoc[]

==== 1.10 Properties / Themes

The `+themes+` property is a list of concepts that are referenced to a vocabulary or knowledge organization system used to classify the resource.  

A theme's `+scheme+` property provides a remote reference to a controlled vocabulary, code list or knowledge organization system.

A concept's `+id+` provides an identifier for the given concept, as well as optional `+title+`, `+description+` and `+url+` properties to further describe the concept as desired.

A concept's optional `+url+` property can provide a remote reference to a given concept (for example, to an online ontology or code registry).

A WCMP metadata record can have one or more themes.

.Example: Themes object with GRIB2 codes
[source,json]
----
"properties": {
  ...
  "themes": [
    {
      "concepts": [
        {
          "id": "0-0-0",
          "title": "Temperature",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/0-0-0"
        },
        {
          "id": "0-1-1",
          "title": "Relative humidity",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/0-1-1"
        },
        {
          "id": "0-2-2",
          "title": "u-component of Wind",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/0-2-2"
        },
        {
          "id": "0-2-3",
          "title": "v-component of Wind",
          "url": "http://codes.wmo.int/grib2/codeflag/4.2/0-2-3"
        }
      ],
      "scheme": "http://codes.wmo.int/grib2/codeflag/4.2"
    }
  ]
  ...
}
----
.Example: Themes object with BUFR4 codes

[source,json]
----
"properties": {
  ...
  "themes": [
    {
      "concepts": [
        {
          "id": "001",
          "title": "Temperature/air temperature",
          "url": "http://codes.wmo.int/bufr4/b/12/001"
        },
        {
          "id": "003",
          "title": "Dewpoint temperature",
          "url": "http://codes.wmo.int/bufr4/b/12/003"
        }
      ],
      "scheme": "http://codes.wmo.int/bufr4/b"
    }
  ]
  ...
}
----
.Example: Themes object with the `+earth-system-discipline+` from the WMO Topic Hierarchy

[source,json]
----
"properties": {
  ...
  "themes": [
    {
      "concepts": [{
        "id": "weather",
        "title": "Weather",
        "url": "http://codes.wmo.int/wis/topic-hierarchy/earth-system-discipline/weather"
      }],
      "scheme": "http://codes.wmo.int/wis/topic-hierarchy/earth-system-discipline"
    }
  ]
  ...
}
----

include::../requirements/core/REQ_themes.adoc[]
include::../requirements/core/REQ_themes_wis2_global_service.adoc[]
include::../recommendations/core/REC_granularity.adoc[]
include::../recommendations/core/PER_themes.adoc[]

==== 1.11 Geospatial and temporal extents

===== 1.11.1 Geospatial extent

The `+geometry+` property is the general bounding spatial extent of the dataset in the geographic coordinate system.  
Geospatial bounding extents provide a useful indicator of the location of the dataset to facilitate search and map displays in the GDC.

.Examples:

[source,json]
----
"geometry": {
  "type": "Polygon",
  "coordinates": [[
    [-142.23, 28.03],
    [-142.23, 82.56],
    [-52.16, 82.56],
    [-52.16, 28.03],
    [-142.23, 28.03]
  ]]
}
----

[source,json]
----
"geometry": {
  "type": "Point",
  "coordinates": [-79.38, 43.65]
}
----

[source,json]
----
"geometry": null
----

include::../requirements/core/REQ_extent_geospatial.adoc[]
include::../recommendations/core/REC_extent_geospatial_point.adoc[]
include::../recommendations/core/REC_extent_geospatial_precision.adoc[]
include::../recommendations/core/REC_extent_geospatial_wis2_global_service.adoc[]

===== 1.11.2 Additional geospatial extents

The `+additionalExtents.spatial+` property is for other geospatial extents associated with the dataset. For example, it may be useful for non-geographic data or for describing multiple sub-areas of a dataset.
The `+additionalExtents.spatial.bbox+` property
provides the ability to list one to many minimum bounding geometries for a given dataset, where:

* The minimum longitude is the westernmost coordinate of the limit of the dataset extent, expressed in longitude decimal degrees as a
signed number between -180 and 180, less than or equal to the maximum longitude;
* The minimum latitude is the southernmost coordinate of the limit of the dataset extent, expressed in latitude decimal degrees as a
signed number between -90 and 90, less than or equal to the maximum latitude;
* The maximum longitude is the easternmost coordinate of the limit of the dataset extent, expressed in longitude decimal degrees as a
signed number between -180 and 180, greater than or equal to the minimum longitude;
* The maximum latitude is the northernmost coordinate of the limit of the dataset extent, expressed in latitude decimal degrees as a
signed number between -90 and 90, greater than or equal to the minimum latitude.

This property also facilitates catalogue searches with geospatial predicate (such as, within extent).

.Example:

[source,json]
----
"additionalExtents": {
  "spatial": {
    "bbox": [
      [-142, 42, -52, 84]
    ],
    "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
  }
}
----

include::../recommendations/core/PER_extent_geospatial.adoc[]

===== 1.11.3 Temporal extent

The `+time+` property describes the general bounding extent of the dataset and the temporal resolution. 

Temporal extents provide a useful indicator of the date and time period of the dataset and facilitate temporal searching in the GDC. 

In addition, the temporal resolution provides a useful indicator of the data update frequency (for example, for real-time datasets). If only times are given for the interval, it is implicitly assumed that those are recurring every day. A null value can be used if a time indication cannot be derived.

.Examples:

[source,json]
----
"time": {
  "date": "2021-10-30"
}
----

[source,json]
----
"time": {
  "timestamp": "2021-10-30T11:11:11Z"
}
----

[source,json]
----
"time": {
  "interval" : ["2020-10-30", "2021-10-30"],
  "resolution": "P1D"
}
----

[source,json]
----
"time": {
  "interval" : ["T00Z", "T23Z"],
  "resolution": "PT1H"
}
----

[source,json]
----
"time": {
  "interval": ["2018-04-22", ".."],
}
----

[source,json]
----
"time": null
----

To ensure clarity, an additional human-readable explanation is given in the `+properties.description+` property.
Further time-related characteristics (for example, frequency of modifications, available data and so forth) should be added in `+properties.themes+`.

Some cases might be more complex due to the product's characteristics.
If necessary, further granularity can be indicated by the `+additionalExtents.temporal+` property (see <<_1_11_4_additional_temporal_extents>>).

.Example: Complex time indication

[source,json]
----
"time": {
  "interval" : ["2018-04-22", ".."]
},
"additionalExtents": {
  "temporal": {
    "interval": [
      [
        "T00Z",
        "PT180H"
      ],
      [
        "T12Z",
        "PT180H"
      ]
    ],
    "resolution": "PT6H",
    "trs": "http://www.opengis.net/def/trs/ISO-8601"
  }
}
----

.Example: Complex time indication further described with themes property

[source,json]
----
"properties": {
  ...
  "description": "ICON-EPS 0.5 deg x 0.5 deg regular lat/lon grid, up to +180h every 6h, runs 00/12 UTC, various parameter, various level, various threshold",
  "themes": [
    {
      "concepts": [
        {"id": "continual"}
      ],
      "scheme": "https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_FrequencyCode"
    }
  ]
}
----

include::../requirements/core/REQ_extent_temporal.adoc[]
include::../recommendations/core/REC_extent_temporal.adoc[]
include::../recommendations/core/PER_extent_temporal_service.adoc[]

===== 1.11.4 Additional temporal extents

The `+additionalExtents.temporal+` property is for describing other temporal extents associated with the dataset. For example, it may be useful to represent multiple time instances or to identify other temporal reference systems. 
Temporal extents can be fully bound or open in either direction.  An `+additionalExtents.temporal.resolution+` property is able to express the temporal granularity at which a given dataset's data are measured, generated or reported.

.Example:

[source,json]
----
"additionalExtents": {
  "temporal": {
    "interval": [
      [
        "T00Z",
        "PT180H"
      ],
      [
        "T12Z",
        "PT180H"
      ]
    ],
    "resolution": "PT6H",
    "trs": "http://www.opengis.net/def/trs/ISO-8601"
  }
}
----

include::../recommendations/core/PER_extent_temporal.adoc[]

==== 1.12 Properties / Contacts

The `+contacts+` property is the information associated with one or more parties responsible for the resource.

.Example: Contacts object with all contact details

[source,json]
----
"properties": {
  ...
  "contacts": [{
    "identifier": "ECCC",
    "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
    "name": "National Inquiry Response Team",
    "phones": [{
      "value": "+18199972800"
    }],
    "emails": [{
      "value":"enviroinfo@ec.gc.ca"
    }],
    "addresses": [{
      "deliveryPoint": [ "77 Westmorland Street, suite 260" ],
      "city": "Fredericton",
      "administrativeArea": "NB",
      "postalCode": "E3B 6Z4",
      "country": "CAN"
    }],
    "links": [{
      "href": "https://example.org/about",
      "rel": "about",
      "type": "text/html"
    }],
    "contactInstructions": "email",
    "roles": ["producer", "host"]
  }]
  ...
}
----
.Example: Contacts object with URL to the relevant homepage

[source,json]
----
"properties": {
  ...
  "contacts": [{
    "organization": "Government of Canada; Environment and Climate Change Canada; Meteorological Service of Canada",
    "links": [{
      "href": "https://example.org/about",
      "rel": "about",
      "type": "text/html"
    }],
    "roles": ["producer"]
  }]
}
----

include::../requirements/core/REQ_contacts.adoc[]
include::../recommendations/core/REC_contacts.adoc[]
include::../recommendations/core/PER_contacts.adoc[]

==== 1.13 Properties / Version

The `+version+` property is the version or edition of the dataset. Datasets may be versioned by an organization, for example, the version of an NWP model or a processing chain/workflow, and data providers can make this information available when there are multiple versions of a dataset over time.

.Example

[source,json]
----
"properties": {
  ...
  "version": "0.1.0"
  ...
}
----

include::../recommendations/core/PER_version.adoc[]

==== 1.14 Properties / Persistent identifiers

The `+externalIds+` property is a persistent (or handle) identifier used to provide a long lasting reference to a digital resource.  Persistent identifiers are commonly used for scientific publications and datasets.

Examples of persistent identifiers include, but are not limited to:

* Digital Object Identifier (https://doi.org[DOI])
* Archival Resource Key (https://arks.org[ARK])
* https://handle.net[Handle]

.Example: Persistent identifiers

[source,json]
----
"properties": {
  ...
  "externalIds": [{
    "scheme": "https://doi.org",
    "value": "10.14287/10000001"
  }, {
    "scheme": "https://handle.net",
    "value": "2381/12775"
  }, {
    "scheme": "https://arks.org",
    "value": "ark:/13030/tf5p30086k"
  }]
  ...
}
----

.Example: Online citation

[source,json]
----
"links": [
  {
    "rel": "cite-as",
    "title": "Cite as: WMO/GAW Ozone Monitoring Community, World Meteorological Organization-Global Atmosphere Watch Programme (WMO-GAW)/World Ozone and Ultraviolet Radiation Data Centre (WOUDC) [Data]. Retrieved [YYYY-MM-DD], from https://woudc.org. A list of all contributors is available on the website. doi:10.14287/10000004",
    "type": "text/html",
    "href": "https://dx.doi.org/10.14287/10000004"
  }
]
----

include::../recommendations/core/REC_pids.adoc[]
include::../recommendations/core/PER_pids.adoc[]

==== 1.15 Properties / Record creation date

The `+created+` property is a single date, being the date that the WCMP metadata record was created. Note that this date is not the start or end time of a given dataset.  See <<_1_11_3_temporal_extent>> for more information on defining dataset temporal extents.

.Example:

[source,json]
----
"properties": {
  ...
  "created": "2021-06-12T23:45:24Z"
  ...
}
----

include::../requirements/core/REQ_record_creation_date.adoc[]

==== 1.16 Properties / Record update date

The `+updated+` property is the date that the WCMP metadata record was last updated. Note, that this date is not the start or end time of a given dataset.  See <<_1_11_3_temporal_extent>> for more information on defining dataset temporal extents.

.Example:

[source,json]
----
"properties": {
  ...
  "updated": "2022-06-12T18:52:39Z"
  ...
}
----

include::../recommendations/core/REC_record_update_date.adoc[]

==== 1.17 Properties / Status

The `+status+` property identifies the life cycle of a given dataset. 

.Example:

[source,json]
----
"properties": {
  "status": {
    "id": "operational",
    "title": "dataset is in 24/7 operation",
    "url": "https://example.org/my-vocab"
  }
}
----

include::../recommendations/core/REC_status.adoc[]

==== 1.18 Properties / WMO data policy

The `+wmo:dataPolicy+` property is a codelist that identifies the classification of the dataset exchange as described by the WMO Unified Data Policy (Resolution 1 (Cg-Ext(2021)))footnote:[Resolution 1 (Cg-Ext(2021)) – WMO Unified Policy for the International Exchange of Earth System Data (World Meteorological Congress: Abridged Final Report of the Extraordinary Session (WMO-No. 1281))] for the international exchange of Earth system data. The code list values are `+core+` or `+recommended+`.  The `+wmo:dataPolicy+` property is required if the metadata record describes a dataset.

Licensing and copyright are expressed via the `+links+` property (see <<_1_19_links_and_distribution_information>>), providing access, license and attribution details as required. Conditions on use of the data should be indicated for transparency and clarification.

.Example: Core data

[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "core"
  ...
}
----

.Example: Recommended data
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
}
----

It is useful to add provider-specific details to have the most detailed information about data policy and additional conditions.

.Example: Recommended data with additional conditions and provider-specific details
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
},
"links": [{
  "rel": "license",
  "href": "https://example.org/license",
  "type": "text/html",
  "title": "EUMETSAT DATA LICENSING"
}]
----

.Example: License for recommended data in the public domain
[source,json]
----
"properties": {
  ...
  "wmo:dataPolicy": "recommended"
  ...
},
"links": [{
  "rel": "license",
  "href": "https://creativecommons.org/publicdomain/zero/1.0/",
  "type": "text/html",
  "title": "CC0 1.0 Deed | CC0 1.0 Universal | Creative Commons"
}]
----

To express rights not addressed by a license, the `+rights+` property can be used as follows:

.Example: Rights
[source,json]
----
"properties": {
 ...
 "rights": "Users are granted free and unrestricted access to this data, without charge and with no conditions on use. Users are requested to attribute the producer of this data. WMO Unified Data Policy (Resolution 1 (Cg-Ext 2021))."
 ...
}
----

include::../requirements/core/REQ_data_policy.adoc[]
include::../recommendations/core/REC_data_policy.adoc[]
include::../recommendations/core/PER_data_policy.adoc[]

==== 1.19 Links and distribution information 
//[[links-distribution]]

===== 1.19.1 Overview

The `+links+` property describes URLs and APIs for accessing the dataset or for subscribing to dataset notifications. Links are the primary mechanism for interacting with the data, and provide an "actionable" workflow to enhance and improve the user experience with "less clicks" for subscriptions and downloads.

The `+links+` property may also describe URLs for related documentation, related data or visual images of the dataset.

The table below provides an overview of the properties of a link object.

.Table. Link properties
|===
|Property|Requirement|Description

|``href``
|**Required**
|The link destination or target, or URL

|``rel``
|Optional
|The relationship that the link bears in the context of the WCMP record.  This is a controlled vocabulary defined
 by link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA link relations] or link:https://codes.wmo.int/wis/link-type[WIS link type] extensions (see table in <<_1_19_5_link_relation_selection>>).

|``type``
|Optional
|The media (or MIME) type of the format of the link

|``hreflang``
|Optional
|The language of the content in the link

|``title``
|Optional
|A human-readable name for the link (can be used for display on search / discovery web portals)

|``channel``
|**Conditional**
|For data made available via MQTT, the topic to which a user may subscribe for notifications and access

|``security``
|Optional
|For access-controlled data, a description of the access control mechanism applied (see <<_1_19_4_access_control>>)

|``distribution``
|Optional
|Value added information about the link to further assist the user (additional document, typical file size, etc.) (see <<_1_19_links_and_distribution_information>>)

|===

For recommended data, the ``links`` property may also provide links to services that implement access control in support of authentication and authorization.  In secure data use cases, a user needs to be able to detect access-controlled data as part of data discovery and evaluation.

.Example: A link object expressing access control using HTTP Basic Authentication for a given data access service

.Example: Access controlled link

[source,json]
----
"links": [{
  "rel": "data",
  "type": "application/json",
  "title": "link to WAF endpoint",
  "href": "https://example.org/data/secure-data",
  "security": {
    "default": {
      "type": "http",
      "scheme": "basic",
      "description": "Please contact the data provider for accessing this secured resource."
    }
  }
}]
----

.Example: Two link objects providing both search and MQTT subscription information

[source,json]
----
"links": [
  {
    "rel": "search",
    "type": "text/html",
    "title": "WOUDC - Data - Station List",
    "href": "https://example.org/data/stations"
  },
  {
    "rel"  : "items",
    "type" : "application/geo+json",
    "title": "WIS2 notification service",
    "href" : "mqtts://example.org",
    "channel": "cache/a/wis2/ca-eccc-msc/data/core/weather/surface-based-observations"
  }
]
----

.Example: A link object providing an API capability

[source,json]
----
"links": [
  {
    "rel": "service",
    "type": "application/json",
    "title": "OGC API - Features service",
    "href": "https://example.org/api"
  }
]
----

.Example: A link object providing a browse graphic

[source,json]
----
"links": [
  {
    "rel": "preview",
    "type": "image/png",
    "title": "Browse graphic",
    "href": "https://example.org/path/to/browse.png"
  }
]
----

===== 1.19.2 Templated links

Templated links allow for specifying a pattern of a link in support of API interaction (where parameter values are variable).

.Example: A templated link object of a Web Map Service (WMS) providing API access to images
[source,json]
----
"linkTemplates": [{
  "rel": "item",
  "type": "image/png",
  "title": "Eumetview",
  "uriTemplate": "https://example.org/geoserver/ows?service=WMS&request=GetMap&version=1.3.0&layers=msg_fes:ir108&styles=&format={format}&crs={crs}&bbox={bbox}&width={width}&height={height}",
  "variables": {
    "crs": {
      "description": "...",
      "type": "string",
      "enum": [
        "EPSG:4326",
        "EPSG:3857"
      ]
    },
    "bbox": {
      "description": "...",
      "type": "array",
      "items": {
        "type": "number",
        "format": "double"
      },
      "minItems": 4,
      "maxItems": 4
    },
    "width": {
      "description": "...",
      "type": "number",
      "format": "integer",
      "minimum": 600,
      "maximum": 5000
    },
    "height": {
      "description": "...",
      "type": "number",
      "format": "integer",
      "minimum": 600,
      "maximum": 5000
    },
    "format": {
      "description": "...",
      "type": "string",
      "enum": [
        "image/geotiff",
        "image/geotiff8",
        "image/gif",
        "image/jpeg",
        "image/png; mode=8bit"
      ]
    },
    "sampleRequest": "https://example.org/geoserver/ows?service=WMS&request=GetMap&version=1.3.0&layers=msg_fes:ir108&styles=&format=image/jpeg&crs=EPSG:4326&bbox=-77,-77,77,77&width=800&height=800"
  }
}]
----

include::../requirements/core/REQ_links.adoc[]
include::../recommendations/core/REC_links.adoc[]
include::../recommendations/core/PER_links.adoc[]

===== 1.19.3 Distribution information

The `+distribution+` property provides information about the format of the dataset, associated documentation and representative examples of the dataset.

Additional distribution information is added to allow more comprehensive discovery services. 

.Example: Links object with the complete distribution information

[source,json]
----
"links": [{
  "rel": "search",
  "type": "text/html",
  "title": "EUMETSAT Datastore",
  "href": "https://example.org/data/map/EO:EUM:DAT:MSG:MSG15-RSS",
  "distribution": {
    "availableFormats": [{
      "name": "native",
      "description": "This is sent in a compressed Submission Information Package (SIP) by default.",
      "numberOfFiles": "288 per day",
      "typicalFilesize": "60 MB",
      "typicalFilename": "MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip",
      "samples": { 
        "href": "https://example.org/data/access/MSG3-SEVI-MSG15-0100-NA-20130208102743.243000000Z-1051616.zip" 
      },
      "documentation": [{
        "rel": "alternate",
        "type": "text/html",
        "title": "SIP documentation and tools",
        "href": "https://www.eumetsat.int/formats#SIP"
      }]
    }]
  }
}]
----

include::../recommendations/core/REC_distribution.adoc[]

===== 1.19.4 Access control

WCMP record links may also provide links to services that implement access control in support of authentication and authorization.  In
secure data use cases, a user needs to be able to detect access-controlled data as part of data discovery and evaluation.  The
example demonstrates how to express access control using HTTP basic authentication for a given data access service.

.Example

[source,json]
----
"links": [{
  "rel": "data",
  "type": "application/json",
  "title": "link to WAF endpoint",
  "href": "https://example.org/data/secure-data",
  "security": {
    "default": {
      "type": "http",
      "scheme": "basic",
      "description": "Please contact the data provider for accessing this secured resource."
    }
  }
}]
----

===== 1.19.5 Link relation selection

Link relations are very important and provide valuable context to help clarify the semantics of a given link or URL.

The table below provides guidance on which link relation to use to identify common types of
links to data and services.

.Table. Link relation selection
|===
|Link type|Link relation (`rel=`)

|Online data archive
|`archives`

|Online documentation
|`about`

|OpenAPI endpoint (such as JSON or YAML)
|`service-desc`

|OpenAPI endpoint in HTML (such as Swagger or ReDoc)
|`service-doc`

|OGC WMS, WFS, WCS, CSW, WPS Capabilities
|`service-desc`

|A single link providing numerous data granules
|`items`

|A link providing a single data granule
|`item`

|A link to numerous stations on which the dataset is based
|`stations`

|A link to a single station on which the dataset is based
|`station`

|citation
|`cite-as`

|A search portal or web application
|`search`

|A zip file of data, or bulk download
|`enclosure`

|A browse graphic of a dataset
|`preview`

|An OGC API endpoint providing a collection description
|`collection`

|===

==== 1.20 Additional properties

A WCMP record can be extended as required for organizational purposes by adding properties (of any type) in the
record.  Additional properties do not render a record non-compliant with WCMP.

.Example:

[source,json]
----
"properties": {
  ...
  "approvalStatus": "approved"
  "_comment": {
    "validationErrors": [
      "error 1",
      "error 2"
    ]
  }
  ...
}
----

include::../recommendations/core/PER_additional_properties.adoc[]

=== 2. WMO Core Metadata Profile resources

==== 2.1 WMO Codes Registry

•	http://codes.wmo.int/wis/contact-role
•	http://codes.wmo.int/wis/global-service-type
•	http://codes.wmo.int/wis/link-type
•	http://codes.wmo.int/wis/resource-type
•	http://codes.wmo.int/wis/topic-hierarchy/centre-id
•	http://codes.wmo.int/wis/topic-hierarchy/data-policy
•	http://codes.wmo.int/wis/topic-hierarchy/earth-system-discipline
•	http://codes.wmo.int/wis/topic-hierarchy/notification-type

==== 2.2 WMO schemas server
Validation schemas, examples and other resources are published at https://schemas.wmo.int/wcmp.
