name: validate schema and examples

on:
  push:
    paths:
      - '**.json'   
      - '**.yaml'   
  pull_request:
    paths:
      - '**.json'   
      - '**.yaml'   

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements 📦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install check-jsonschema
    - name: Validate examples
      run: |
        for e in examples/*.json; do check-jsonschema --schemafile schemas/wcmp2-bundled.json $e; done
